SECTION code_user

PUBLIC PLY_AKG_INIT
PUBLIC PLY_AKG_PLAY
PUBLIC PLY_AKG_STOP
PUBLIC PLY_AKG_INITSOUNDEFFECTS
PUBLIC PLY_AKG_PLAYSOUNDEFFECT
PUBLIC _SONG


defc PLY_AKG_FULL_INIT_CODE = 1
defc PLY_AKG_OFFSET1B = 1
defc PLY_AKG_USE_HOOKS = 1
defc PLY_AKG_STOP_SOUNDS = 1
defc PLY_AKG_BITFORSOUND = 2
defc PLY_AKG_OFFSET2B = 2
defc PLY_AKG_SOUNDEFFECTDATA_OFFSETINVERTEDVOLUME = 2
PLY_AKG_START:
PLY_AKG_OPCODE_ADD_HL_BC_MSB:
	jp PLY_AKG_INIT
defc PLY_AKG_SOUNDEFFECTDATA_OFFSETSPEED = 1
defc PLY_AKG_BITFORNOISE = 2
PLY_AKG_SOUNDEFFECTDATA_OFFSETCURRENTSTEP:
	jp PLY_AKG_PLAY
defc PLY_AKG_CHANNEL_SOUNDEFFECTDATASIZE = 2
    jp PLY_AKG_INITTABLEORA_END
PLY_AKG_INITSOUNDEFFECTS:
PLY_AKG_OPCODE_ADD_HL_BC_LSB:
	ld (PLY_AKG_PTSOUNDEFFECTTABLE+1),hl
    ret 
PLY_AKG_PLAYSOUNDEFFECT:
	dec a
PLY_AKG_PTSOUNDEFFECTTABLE:
	ld hl,0
    ld e,a
    ld d,0
    add hl,de
    add hl,de
    ld e,(hl)
    inc hl
    ld d,(hl)
    ld a,(de)
    inc de
    ex af,af'
    ld a,b
    ld hl,PLY_AKG_CHANNEL1_SOUNDEFFECTDATA
    ld b,0
defc PLY_AKG_OPCODE_INC_HL = 1
    sla c
    sla c
    sla c
    add hl,bc
    ld (hl),e
    inc hl
PLY_AKG_OPCODE_DEC_HL:
	ld (hl),d
    inc hl
    ld (hl),a
    inc hl
    ld (hl),0
    inc hl
    ex af,af'
    ld (hl),a
    ret 
PLY_AKG_STOPSOUNDEFFECTFROMCHANNEL:
	add a,a
    add a,a
PLY_AKG_OPCODE_SCF:
	add a,a
    ld e,a
    ld d,0
    ld hl,PLY_AKG_CHANNEL1_SOUNDEFFECTDATA
    add hl,de
    ld (hl),d
    inc hl
    ld (hl),d
PLY_AKG_OPCODE_SBC_HL_BC_LSB:
	ret 
PLY_AKG_PLAYSOUNDEFFECTSSTREAM:
	rla 
    rla 
    ld ix,PLY_AKG_CHANNEL1_SOUNDEFFECTDATA
    ld iy,PLY_AKG_PSGREG8
    ld hl,PLY_AKG_PSGREG01_INSTR+1
    exx
    ld c,a
    call PLY_AKG_PSES_PLAY
    ld ix,PLY_AKG_CHANNEL2_SOUNDEFFECTDATA
    ld iy,PLY_AKG_PSGREG9
    exx
    ld hl,PLY_AKG_PSGREG23_INSTR+1
    exx
    srl c
    call PLY_AKG_PSES_PLAY
    ld ix,PLY_AKG_CHANNEL3_SOUNDEFFECTDATA
    ld iy,PLY_AKG_PSGREG10
    exx
    ld hl,PLY_AKG_PSGREG45_INSTR+1
    exx
    rr c
    call PLY_AKG_PSES_PLAY
    ld a,c
    ret 
PLY_AKG_PSES_PLAY:
	ld l,(ix+0)
    ld h,(ix+1)
    ld a,l
    or h
    ret z
PLY_AKG_PSES_READFIRSTBYTE:
	ld a,(hl)
    inc hl
    ld b,a
    rra 
    jr c,PLY_AKG_PSES_SOFTWAREORSOFTWAREANDHARDWARE
    rra 
    jr c,PLY_AKG_PSES_HARDWAREONLY
    rra 
    jr c,PLY_AKG_PSES_S_ENDORLOOP
    call PLY_AKG_PSES_MANAGEVOLUMEFROMA_FILTER4BITS
    rl b
    call PLY_AKG_PSES_READNOISEIFNEEDEDANDOPENORCLOSENOISECHANNEL
    set 2,c
    jr PLY_AKG_PSES_SAVEPOINTERANDEXIT
PLY_AKG_PSES_S_ENDORLOOP:
	rra 
    jr c,PLY_AKG_PSES_S_LOOP
    xor a
    ld (ix+0),a
    ld (ix+1),a
    ret 
PLY_AKG_PSES_S_LOOP:
	ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    jr PLY_AKG_PSES_READFIRSTBYTE
PLY_AKG_PSES_SAVEPOINTERANDEXIT:
	ld a,(ix+3)
    cp (ix+4)
    jr c,PLY_AKG_PSES_NOTREACHED
defc PLY_AKG_OPCODE_OR_A = 2
    ld (ix+3),0
    defb 221
    defb 117
    defb 0
    defb 221
    defb 116
    defb 1
    ret 
PLY_AKG_PSES_NOTREACHED:
	inc (ix+3)
    ret 
defc PLY_AKG_OPCODE_ADD_A_IMMEDIATE = 2
PLY_AKG_PSES_HARDWAREONLY:
	call PLY_AKG_PSES_SHARED_READRETRIGHARDWAREENVPERIODNOISE
    set 2,c
    jr PLY_AKG_PSES_SAVEPOINTERANDEXIT
PLY_AKG_PSES_SOFTWAREORSOFTWAREANDHARDWARE:
	rra 
    jr c,PLY_AKG_PSES_SOFTWAREANDHARDWARE
    call PLY_AKG_PSES_MANAGEVOLUMEFROMA_FILTER4BITS
    rl b
    call PLY_AKG_PSES_READNOISEIFNEEDEDANDOPENORCLOSENOISECHANNEL
PLY_AKG_OPCODE_SUB_IMMEDIATE:
	res 2,c
    call PLY_AKG_PSES_READSOFTWAREPERIOD
    jr PLY_AKG_PSES_SAVEPOINTERANDEXIT
PLY_AKG_PSES_SOFTWAREANDHARDWARE:
	call PLY_AKG_PSES_SHARED_READRETRIGHARDWAREENVPERIODNOISE
    call PLY_AKG_PSES_READSOFTWAREPERIOD
    res 2,c
    jr PLY_AKG_PSES_SAVEPOINTERANDEXIT
PLY_AKG_PSES_SHARED_READRETRIGHARDWAREENVPERIODNOISE:
	rra 
    jr nc,PLY_AKG_PSES_H_AFTERRETRIG
    ld d,a
    ld a,255
PLY_AKG_OPCODE_SBC_HL_BC_MSB:
	ld (PLY_AKG_PSGREG13_OLDVALUE+1),a
    ld a,d
PLY_AKG_PSES_H_AFTERRETRIG:
	and 7
    add a,8
    ld (PLY_AKG_PSGREG13_INSTR+1),a
    rl b
    call PLY_AKG_PSES_READNOISEIFNEEDEDANDOPENORCLOSENOISECHANNEL
    call PLY_AKG_PSES_READHARDWAREPERIOD
    ld a,16
    jp PLY_AKG_PSES_MANAGEVOLUMEFROMA_HARD
PLY_AKG_PSES_READNOISEIFNEEDEDANDOPENORCLOSENOISECHANNEL:
	jr c,PLY_AKG_PSES_READNOISEANDOPENNOISECHANNEL_OPENNOISE
    set 5,c
    ret 
PLY_AKG_PSES_READNOISEANDOPENNOISECHANNEL_OPENNOISE:
	ld a,(hl)
    ld (PLY_AKG_PSGREG6),a
    inc hl
    res 5,c
    ret 
PLY_AKG_PSES_READHARDWAREPERIOD:
	ld a,(hl)
    ld (PLY_AKG_PSGHARDWAREPERIOD_INSTR+1),a
    inc hl
    ld a,(hl)
    ld (PLY_AKG_PSGHARDWAREPERIOD_INSTR+2),a
    inc hl
    ret 
PLY_AKG_PSES_READSOFTWAREPERIOD:
	ld a,(hl)
    inc hl
    exx
    ld (hl),a
    inc hl
    exx
    ld a,(hl)
    inc hl
    exx
    ld (hl),a
    exx
    ret 
PLY_AKG_PSES_MANAGEVOLUMEFROMA_FILTER4BITS:
	and 15
PLY_AKG_PSES_MANAGEVOLUMEFROMA_HARD:
	sub (ix+2)
    jr nc,PLY_AKG_PSES_MVFA_NOOVERFLOW
    xor a
PLY_AKG_PSES_MVFA_NOOVERFLOW:
	ld (iy+0),a
    ret 
PLY_AKG_CHANNEL1_SOUNDEFFECTDATA:
	defw 0
PLY_AKG_CHANNEL1_SOUNDEFFECTINVERTEDVOLUME:
	defb 0
PLY_AKG_CHANNEL1_SOUNDEFFECTCURRENTSTEP:
	defb 0
PLY_AKG_CHANNEL1_SOUNDEFFECTSPEED:
	defb 0
    defb 0
    defb 0
    defb 0
PLY_AKG_CHANNEL2_SOUNDEFFECTDATA:
	defb 0
    defb 0
    defb 0
    defb 0
    defb 0
    defb 0
    defb 0
    defb 0
PLY_AKG_CHANNEL3_SOUNDEFFECTDATA:
	defb 0
    defb 0
    defb 0
    defb 0
    defb 0
    defb 0
    defb 0
    defb 0
PLY_AKG_INIT:
	ld de,4
    add hl,de
    ld de,PLY_AKG_ARPEGGIOSTABLE+1
    ldi
    ldi
    ld de,PLY_AKG_PITCHESTABLE+1
    ldi
    ldi
    ld de,PLY_AKG_INSTRUMENTSTABLE+1
    ldi
    ldi
    ld c,(hl)
    inc hl
    ld b,(hl)
    inc hl
    ld (PLY_AKG_CHANNEL_READEFFECTS_EFFECTBLOCKS1+1),bc
    ld (PLY_AKG_CHANNEL_READEFFECTS_EFFECTBLOCKS2+1),bc
    add a,a
    ld e,a
    ld d,0
    add hl,de
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    ld de,5
    add hl,de
    ld de,PLY_AKG_CHANNEL3_READCELLEND+1
    ldi
    ld de,PLY_AKG_CHANNEL1_NOTE+1
    ldi
    ld (PLY_AKG_READLINKER+1),hl
    ld hl,PLY_AKG_INITTABLE0
    ld bc,3328
    call PLY_AKG_INIT_READWORDSANDFILL
    inc c
    ld hl,PLY_AKG_INITTABLE0_END
    ld b,3
    call PLY_AKG_INIT_READWORDSANDFILL
    ld hl,PLY_AKG_INITTABLE1_END
    ld bc,3511
    call PLY_AKG_INIT_READWORDSANDFILL
    ld hl,(PLY_AKG_INSTRUMENTSTABLE+1)
    ld e,(hl)
    inc hl
    ld d,(hl)
    ex de,hl
    inc hl
    ld (PLY_AKG_ENDWITHOUTLOOP+1),hl
    ld (PLY_AKG_CHANNEL1_PTINSTRUMENT+1),hl
    ld (PLY_AKG_CHANNEL2_PTINSTRUMENT+1),hl
    ld (PLY_AKG_CHANNEL3_PTINSTRUMENT+1),hl
    ld hl,0
    ld (PLY_AKG_CHANNEL1_SOUNDEFFECTDATA),hl
    ld (PLY_AKG_CHANNEL2_SOUNDEFFECTDATA),hl
    ld (PLY_AKG_CHANNEL3_SOUNDEFFECTDATA),hl
    ret 
PLY_AKG_INIT_READWORDSANDFILL_LOOP:
	ld e,(hl)
    inc hl
    ld d,(hl)
    inc hl
    ld a,c
    ld (de),a
PLY_AKG_INIT_READWORDSANDFILL:
	djnz PLY_AKG_INIT_READWORDSANDFILL_LOOP
    ret 
PLY_AKG_INITTABLE0:
	defw PLY_AKG_CHANNEL1_INVERTEDVOLUMEINTEGERANDDECIMAL+1
    defw PLY_AKG_CHANNEL1_INVERTEDVOLUMEINTEGER
    defw PLY_AKG_CHANNEL2_INVERTEDVOLUMEINTEGERANDDECIMAL+1
    defw PLY_AKG_CHANNEL2_INVERTEDVOLUMEINTEGER
    defw PLY_AKG_CHANNEL3_INVERTEDVOLUMEINTEGERANDDECIMAL+1
    defw PLY_AKG_CHANNEL3_INVERTEDVOLUMEINTEGER
    defw PLY_AKG_CHANNEL1_PITCHTABLE_END+1
    defw PLY_AKG_CHANNEL1_PITCHTABLE_END+2
    defw PLY_AKG_CHANNEL2_PITCHTABLE_END+1
    defw PLY_AKG_CHANNEL2_PITCHTABLE_END+2
    defw PLY_AKG_CHANNEL3_PITCHTABLE_END+1
    defw PLY_AKG_CHANNEL3_PITCHTABLE_END+2
PLY_AKG_INITTABLE0_END:
PLY_AKG_INITTABLE1:
	defw PLY_AKG_PATTERNDECREASINGHEIGHT+1
    defw PLY_AKG_TICKDECREASINGCOUNTER+1
PLY_AKG_INITTABLE1_END:
PLY_AKG_INITTABLEORA:
	defw PLY_AKG_CHANNEL1_ISVOLUMESLIDE
    defw PLY_AKG_CHANNEL2_ISVOLUMESLIDE
    defw PLY_AKG_CHANNEL3_ISVOLUMESLIDE
    defw PLY_AKG_CHANNEL1_ISARPEGGIOTABLE
    defw PLY_AKG_CHANNEL2_ISARPEGGIOTABLE
    defw PLY_AKG_CHANNEL3_ISARPEGGIOTABLE
    defw PLY_AKG_CHANNEL1_ISPITCHTABLE
    defw PLY_AKG_CHANNEL2_ISPITCHTABLE
    defw PLY_AKG_CHANNEL3_ISPITCHTABLE
    defw PLY_AKG_CHANNEL1_ISPITCH
    defw PLY_AKG_CHANNEL2_ISPITCH
    defw PLY_AKG_CHANNEL3_ISPITCH
PLY_AKG_INITTABLEORA_END:
PLY_AKG_STOP:
	ld (PLY_AKG_PSGREG13_END+1),sp
    xor a
    ld l,a
    ld h,a
    ld (PLY_AKG_PSGREG8),a
    ld (PLY_AKG_PSGREG9),hl
    ld a,63
    jp PLY_AKG_SENDPSGREGISTERS
PLY_AKG_PLAY:
	ld (PLY_AKG_PSGREG13_END+1),sp
PLY_AKG_TICKDECREASINGCOUNTER:
	ld a,1
    dec a
    jp nz,PLY_AKG_SETSPEEDBEFOREPLAYSTREAMS
PLY_AKG_PATTERNDECREASINGHEIGHT:
	ld a,1
    dec a
    jr nz,PLY_AKG_SETCURRENTLINEBEFOREREADLINE
PLY_AKG_READLINKER:
PLY_AKG_READLINKER_PTLINKER:
	ld sp,0
    pop hl
    ld a,l
    or h
    jr nz,PLY_AKG_READLINKER_NOLOOP
    pop hl
    ld sp,hl
    pop hl
PLY_AKG_READLINKER_NOLOOP:
	ld (PLY_AKG_CHANNEL1_READTRACK+1),hl
    pop hl
    ld (PLY_AKG_CHANNEL2_READTRACK+1),hl
    pop hl
    ld (PLY_AKG_CHANNEL3_READTRACK+1),hl
    pop hl
    ld (PLY_AKG_READLINKER+1),sp
    ld sp,hl
    pop hl
    ld c,l
    pop hl
    pop hl
    ld (PLY_AKG_SPEEDTRACK_PTTRACK+1),hl
    xor a
    ld (PLY_AKG_READLINE+1),a
    ld (PLY_AKG_SPEEDTRACK_END+1),a
    ld (PLY_AKG_CHANNEL1_READCELLEND+1),a
    ld (PLY_AKG_CHANNEL2_READCELLEND+1),a
    ld a,c
PLY_AKG_SETCURRENTLINEBEFOREREADLINE:
	ld (PLY_AKG_PATTERNDECREASINGHEIGHT+1),a
PLY_AKG_READLINE:
PLY_AKG_SPEEDTRACK_WAITCOUNTER:
	ld a,0
    sub 1
    jr nc,PLY_AKG_SPEEDTRACK_MUSTWAIT
PLY_AKG_SPEEDTRACK_PTTRACK:
	ld hl,0
    ld a,(hl)
    inc hl
    srl a
    jr c,PLY_AKG_SPEEDTRACK_STOREPOINTERANDWAITCOUNTER
    jr nz,PLY_AKG_SPEEDTRACK_NORMALVALUE
    ld a,(hl)
    inc hl
PLY_AKG_SPEEDTRACK_NORMALVALUE:
	ld (PLY_AKG_CHANNEL3_READCELLEND+1),a
    xor a
PLY_AKG_SPEEDTRACK_STOREPOINTERANDWAITCOUNTER:
	ld (PLY_AKG_SPEEDTRACK_PTTRACK+1),hl
PLY_AKG_SPEEDTRACK_MUSTWAIT:
	ld (PLY_AKG_READLINE+1),a
PLY_AKG_SPEEDTRACK_END:
PLY_AKG_CHANNEL1_WAITCOUNTER:
	ld a,0
    sub 1
    jr c,PLY_AKG_CHANNEL1_READTRACK
    ld (PLY_AKG_SPEEDTRACK_END+1),a
    jp PLY_AKG_CHANNEL1_READCELLEND
PLY_AKG_CHANNEL1_READTRACK:
PLY_AKG_CHANNEL1_PTTRACK:
	ld hl,0
    ld c,(hl)
    inc hl
    ld a,c
    and 63
    cp 60
    jr c,PLY_AKG_CHANNEL1_NOTE
    sub 60
    jp z,PLY_AKG_CHANNEL1_MAYBEEFFECTS
    dec a
    jr z,PLY_AKG_CHANNEL1_WAIT
    dec a
    jr z,PLY_AKG_CHANNEL1_SMALLWAIT
    ld a,(hl)
    inc hl
    jr PLY_AKG_CHANNEL1_AFTERNOTEKNOWN
PLY_AKG_CHANNEL1_SMALLWAIT:
	ld a,c
    rlca 
    rlca 
    and 3
    inc a
    ld (PLY_AKG_SPEEDTRACK_END+1),a
    jr PLY_AKG_CHANNEL1_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL1_WAIT:
	ld a,(hl)
    ld (PLY_AKG_SPEEDTRACK_END+1),a
    inc hl
    jr PLY_AKG_CHANNEL1_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL1_SAMEINSTRUMENT:
PLY_AKG_CHANNEL1_PTBASEINSTRUMENT:
	ld de,0
    ld (PLY_AKG_CHANNEL1_PTINSTRUMENT+1),de
    jr PLY_AKG_CHANNEL1_AFTERINSTRUMENT
PLY_AKG_CHANNEL1_NOTE:
PLY_AKG_BASENOTEINDEX:
	add a,0
PLY_AKG_CHANNEL1_AFTERNOTEKNOWN:
	ld (PLY_AKG_CHANNEL1_TRACKNOTE+1),a
    rl c
    jr nc,PLY_AKG_CHANNEL1_SAMEINSTRUMENT
    ld a,(hl)
    inc hl
    exx
    ld l,a
    ld h,0
    add hl,hl
PLY_AKG_INSTRUMENTSTABLE:
	ld de,0
    add hl,de
    ld sp,hl
    pop hl
    ld a,(hl)
    inc hl
    ld (PLY_AKG_CHANNEL1_INSTRUMENTSPEED+1),a
    ld (PLY_AKG_CHANNEL1_PTINSTRUMENT+1),hl
    ld (PLY_AKG_CHANNEL1_SAMEINSTRUMENT+1),hl
    exx
PLY_AKG_CHANNEL1_AFTERINSTRUMENT:
	ex de,hl
    xor a
    ld l,a
    ld h,a
    ld (PLY_AKG_CHANNEL1_PITCHTABLE_END+1),hl
    ld (PLY_AKG_CHANNEL1_ARPEGGIOTABLECURRENTSTEP+1),a
    ld (PLY_AKG_CHANNEL1_PITCHTABLECURRENTSTEP+1),a
    ld (PLY_AKG_CHANNEL1_INSTRUMENTSTEP+2),a
    ld a,183
    ld (PLY_AKG_CHANNEL1_ISPITCH),a
    ld a,(PLY_AKG_CHANNEL1_ARPEGGIOBASESPEED)
    ld (PLY_AKG_CHANNEL1_ARPEGGIOTABLESPEED),a
    ld a,(PLY_AKG_CHANNEL1_PITCHBASESPEED)
    ld (PLY_AKG_CHANNEL1_PITCHTABLESPEED),a
    ld hl,(PLY_AKG_CHANNEL1_ARPEGGIOTABLEBASE)
    ld (PLY_AKG_CHANNEL1_ARPEGGIOTABLE+1),hl
    ld hl,(PLY_AKG_CHANNEL1_PITCHTABLEBASE)
    ld (PLY_AKG_CHANNEL1_PITCHTABLE+1),hl
    ex de,hl
    rl c
    jp c,PLY_AKG_CHANNEL1_READEFFECTS
PLY_AKG_CHANNEL1_BEFOREEND_STORECELLPOINTER:
	ld (PLY_AKG_CHANNEL1_READTRACK+1),hl
PLY_AKG_CHANNEL1_READCELLEND:
PLY_AKG_CHANNEL2_WAITCOUNTER:
	ld a,0
    sub 1
    jr c,PLY_AKG_CHANNEL2_READTRACK
    ld (PLY_AKG_CHANNEL1_READCELLEND+1),a
    jp PLY_AKG_CHANNEL2_READCELLEND
PLY_AKG_CHANNEL2_READTRACK:
PLY_AKG_CHANNEL2_PTTRACK:
	ld hl,0
    ld c,(hl)
    inc hl
    ld a,c
    and 63
    cp 60
    jr c,PLY_AKG_CHANNEL2_NOTE
    sub 60
    jp z,PLY_AKG_CHANNEL1_READEFFECTSEND
    dec a
    jr z,PLY_AKG_CHANNEL2_WAIT
    dec a
    jr z,PLY_AKG_CHANNEL2_SMALLWAIT
    ld a,(hl)
    inc hl
    jr PLY_AKG_CHANNEL2_AFTERNOTEKNOWN
PLY_AKG_CHANNEL2_SMALLWAIT:
	ld a,c
    rlca 
    rlca 
    and 3
    inc a
    ld (PLY_AKG_CHANNEL1_READCELLEND+1),a
    jr PLY_AKG_CHANNEL2_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL2_WAIT:
	ld a,(hl)
    ld (PLY_AKG_CHANNEL1_READCELLEND+1),a
    inc hl
    jr PLY_AKG_CHANNEL2_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL2_SAMEINSTRUMENT:
PLY_AKG_CHANNEL2_PTBASEINSTRUMENT:
	ld de,0
    ld (PLY_AKG_CHANNEL2_PTINSTRUMENT+1),de
    jr PLY_AKG_CHANNEL2_AFTERINSTRUMENT
PLY_AKG_CHANNEL2_NOTE:
	ld b,a
    ld a,(PLY_AKG_CHANNEL1_NOTE+1)
    add a,b
PLY_AKG_CHANNEL2_AFTERNOTEKNOWN:
	ld (PLY_AKG_CHANNEL2_TRACKNOTE+1),a
    rl c
    jr nc,PLY_AKG_CHANNEL2_SAMEINSTRUMENT
    ld a,(hl)
    inc hl
    exx
    ld e,a
    ld d,0
    ld hl,(PLY_AKG_INSTRUMENTSTABLE+1)
    add hl,de
    add hl,de
    ld sp,hl
    pop hl
    ld a,(hl)
    inc hl
    ld (PLY_AKG_CHANNEL2_INSTRUMENTSPEED+1),a
    ld (PLY_AKG_CHANNEL2_PTINSTRUMENT+1),hl
    ld (PLY_AKG_CHANNEL2_SAMEINSTRUMENT+1),hl
    exx
PLY_AKG_CHANNEL2_AFTERINSTRUMENT:
	ex de,hl
    xor a
    ld l,a
    ld h,a
    ld (PLY_AKG_CHANNEL2_PITCHTABLE_END+1),hl
    ld (PLY_AKG_CHANNEL2_ARPEGGIOTABLECURRENTSTEP+1),a
    ld (PLY_AKG_CHANNEL2_PITCHTABLECURRENTSTEP+1),a
    ld (PLY_AKG_CHANNEL2_INSTRUMENTSTEP+2),a
    ld a,183
    ld (PLY_AKG_CHANNEL2_ISPITCH),a
    ld a,(PLY_AKG_CHANNEL2_ARPEGGIOBASESPEED)
    ld (PLY_AKG_CHANNEL2_ARPEGGIOTABLESPEED),a
    ld a,(PLY_AKG_CHANNEL2_PITCHBASESPEED)
    ld (PLY_AKG_CHANNEL2_PITCHTABLESPEED),a
    ld hl,(PLY_AKG_CHANNEL2_ARPEGGIOTABLEBASE)
    ld (PLY_AKG_CHANNEL2_ARPEGGIOTABLE+1),hl
    ld hl,(PLY_AKG_CHANNEL2_PITCHTABLEBASE)
    ld (PLY_AKG_CHANNEL2_PITCHTABLE+1),hl
    ex de,hl
    rl c
    jp c,PLY_AKG_CHANNEL2_READEFFECTS
PLY_AKG_CHANNEL2_BEFOREEND_STORECELLPOINTER:
	ld (PLY_AKG_CHANNEL2_READTRACK+1),hl
PLY_AKG_CHANNEL2_READCELLEND:
PLY_AKG_CHANNEL3_WAITCOUNTER:
	ld a,0
    sub 1
    jr c,PLY_AKG_CHANNEL3_READTRACK
    ld (PLY_AKG_CHANNEL2_READCELLEND+1),a
    jp PLY_AKG_CHANNEL3_READCELLEND
PLY_AKG_CHANNEL3_READTRACK:
PLY_AKG_CHANNEL3_PTTRACK:
	ld hl,0
    ld c,(hl)
    inc hl
    ld a,c
    and 63
    cp 60
    jr c,PLY_AKG_CHANNEL3_NOTE
    sub 60
    jp z,PLY_AKG_CHANNEL2_READEFFECTSEND
    dec a
    jr z,PLY_AKG_CHANNEL3_WAIT
    dec a
    jr z,PLY_AKG_CHANNEL3_SMALLWAIT
    ld a,(hl)
    inc hl
    jr PLY_AKG_CHANNEL3_AFTERNOTEKNOWN
PLY_AKG_CHANNEL3_SMALLWAIT:
	ld a,c
    rlca 
    rlca 
    and 3
    inc a
    ld (PLY_AKG_CHANNEL2_READCELLEND+1),a
    jr PLY_AKG_CHANNEL3_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL3_WAIT:
	ld a,(hl)
    ld (PLY_AKG_CHANNEL2_READCELLEND+1),a
    inc hl
    jr PLY_AKG_CHANNEL3_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL3_SAMEINSTRUMENT:
PLY_AKG_CHANNEL3_PTBASEINSTRUMENT:
	ld de,0
    ld (PLY_AKG_CHANNEL3_PTINSTRUMENT+1),de
    jr PLY_AKG_CHANNEL3_AFTERINSTRUMENT
PLY_AKG_CHANNEL3_NOTE:
	ld b,a
    ld a,(PLY_AKG_CHANNEL1_NOTE+1)
    add a,b
PLY_AKG_CHANNEL3_AFTERNOTEKNOWN:
	ld (PLY_AKG_CHANNEL3_TRACKNOTE+1),a
    rl c
    jr nc,PLY_AKG_CHANNEL3_SAMEINSTRUMENT
    ld a,(hl)
    inc hl
    exx
    ld e,a
    ld d,0
    ld hl,(PLY_AKG_INSTRUMENTSTABLE+1)
    add hl,de
    add hl,de
    ld sp,hl
    pop hl
    ld a,(hl)
    inc hl
    ld (PLY_AKG_CHANNEL3_INSTRUMENTSPEED+1),a
    ld (PLY_AKG_CHANNEL3_PTINSTRUMENT+1),hl
    ld (PLY_AKG_CHANNEL3_SAMEINSTRUMENT+1),hl
    exx
PLY_AKG_CHANNEL3_AFTERINSTRUMENT:
	ex de,hl
    xor a
    ld l,a
    ld h,a
    ld (PLY_AKG_CHANNEL3_PITCHTABLE_END+1),hl
    ld (PLY_AKG_CHANNEL3_ARPEGGIOTABLECURRENTSTEP+1),a
    ld (PLY_AKG_CHANNEL3_PITCHTABLECURRENTSTEP+1),a
    ld (PLY_AKG_CHANNEL3_INSTRUMENTSTEP+2),a
    ld a,183
    ld (PLY_AKG_CHANNEL3_ISPITCH),a
    ld a,(PLY_AKG_CHANNEL3_ARPEGGIOBASESPEED)
    ld (PLY_AKG_CHANNEL3_ARPEGGIOTABLESPEED),a
    ld a,(PLY_AKG_CHANNEL3_PITCHBASESPEED)
    ld (PLY_AKG_CHANNEL3_PITCHTABLESPEED),a
    ld hl,(PLY_AKG_CHANNEL3_ARPEGGIOTABLEBASE)
    ld (PLY_AKG_CHANNEL3_ARPEGGIOTABLE+1),hl
    ld hl,(PLY_AKG_CHANNEL3_PITCHTABLEBASE)
    ld (PLY_AKG_CHANNEL3_PITCHTABLE+1),hl
    ex de,hl
    rl c
    jp c,PLY_AKG_CHANNEL3_READEFFECTS
PLY_AKG_CHANNEL3_BEFOREEND_STORECELLPOINTER:
	ld (PLY_AKG_CHANNEL3_READTRACK+1),hl
PLY_AKG_CHANNEL3_READCELLEND:
PLY_AKG_CURRENTSPEED:
	ld a,0
PLY_AKG_SETSPEEDBEFOREPLAYSTREAMS:
	ld (PLY_AKG_TICKDECREASINGCOUNTER+1),a
defc PLY_AKG_CHANNEL1_INVERTEDVOLUMEINTEGER = 2
PLY_AKG_CHANNEL1_INVERTEDVOLUMEINTEGERANDDECIMAL:
	ld hl,0
PLY_AKG_CHANNEL1_ISVOLUMESLIDE:
	or a
    jr nc,PLY_AKG_CHANNEL1_VOLUMESLIDE_END
PLY_AKG_CHANNEL1_VOLUMESLIDEVALUE:
	ld de,0
    add hl,de
    bit 7,h
    jr z,PLY_AKG_CHANNEL1_VOLUMENOTOVERFLOW
    ld h,0
    jr PLY_AKG_CHANNEL1_VOLUMESETAGAIN
PLY_AKG_CHANNEL1_VOLUMENOTOVERFLOW:
	ld a,h
    cp 16
    jr c,PLY_AKG_CHANNEL1_VOLUMESETAGAIN
    ld h,15
PLY_AKG_CHANNEL1_VOLUMESETAGAIN:
	ld (PLY_AKG_CHANNEL1_INVERTEDVOLUMEINTEGERANDDECIMAL+1),hl
PLY_AKG_CHANNEL1_VOLUMESLIDE_END:
	ld a,h
    ld (PLY_AKG_CHANNEL1_GENERATEDCURRENTINVERTEDVOLUME+1),a
    ld c,0
PLY_AKG_CHANNEL1_ISARPEGGIOTABLE:
	or a
    jr nc,PLY_AKG_CHANNEL1_ARPEGGIOTABLE_END
PLY_AKG_CHANNEL1_ARPEGGIOTABLE:
	ld hl,0
    ld a,(hl)
    cp 128
    jr nz,PLY_AKG_CHANNEL1_ARPEGGIOTABLE_AFTERLOOPTEST
    inc hl
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    ld a,(hl)
PLY_AKG_CHANNEL1_ARPEGGIOTABLE_AFTERLOOPTEST:
	ld c,a
    ld a,(PLY_AKG_CHANNEL1_ARPEGGIOTABLESPEED)
    ld d,a
PLY_AKG_CHANNEL1_ARPEGGIOTABLECURRENTSTEP:
	ld a,0
    inc a
    cp d
    jr c,PLY_AKG_CHANNEL1_ARPEGGIOTABLE_BEFOREEND_SAVESTEP
    inc hl
    ld (PLY_AKG_CHANNEL1_ARPEGGIOTABLE+1),hl
    xor a
PLY_AKG_CHANNEL1_ARPEGGIOTABLE_BEFOREEND_SAVESTEP:
	ld (PLY_AKG_CHANNEL1_ARPEGGIOTABLECURRENTSTEP+1),a
PLY_AKG_CHANNEL1_ARPEGGIOTABLE_END:
	ld de,0
PLY_AKG_CHANNEL1_ISPITCHTABLE:
	or a
    jr nc,PLY_AKG_CHANNEL1_PITCHTABLE_END
PLY_AKG_CHANNEL1_PITCHTABLE:
	ld sp,0
    pop de
    pop hl
    ld a,(PLY_AKG_CHANNEL1_PITCHTABLESPEED)
    ld b,a
PLY_AKG_CHANNEL1_PITCHTABLECURRENTSTEP:
	ld a,0
    inc a
    cp b
    jr c,PLY_AKG_CHANNEL1_PITCHTABLE_BEFOREEND_SAVESTEP
    ld (PLY_AKG_CHANNEL1_PITCHTABLE+1),hl
    xor a
PLY_AKG_CHANNEL1_PITCHTABLE_BEFOREEND_SAVESTEP:
	ld (PLY_AKG_CHANNEL1_PITCHTABLECURRENTSTEP+1),a
PLY_AKG_CHANNEL1_PITCHTABLE_END:
PLY_AKG_CHANNEL1_PITCH:
	ld hl,0
PLY_AKG_CHANNEL1_ISPITCH:
	or a
    jr nc,PLY_AKG_CHANNEL1_PITCH_END
    defb 221
    defb 105
PLY_AKG_CHANNEL1_PITCHTRACK:
	ld bc,0
    or a
PLY_AKG_CHANNEL1_PITCHTRACKADDORSBC_16BITS:
	nop
    add hl,bc
PLY_AKG_CHANNEL1_PITCHTRACKDECIMALCOUNTER:
	ld a,0
defc PLY_AKG_CHANNEL1_PITCHTRACKDECIMALVALUE = 1
PLY_AKG_CHANNEL1_PITCHTRACKDECIMALINSTR:
	add a,0
    ld (PLY_AKG_CHANNEL1_PITCHTRACKDECIMALCOUNTER+1),a
    jr nc,PLY_AKG_CHANNEL1_PITCHNOCARRY
PLY_AKG_CHANNEL1_PITCHTRACKINTEGERADDORSUB:
	inc hl
PLY_AKG_CHANNEL1_PITCHNOCARRY:
	ld (PLY_AKG_CHANNEL1_PITCHTABLE_END+1),hl
PLY_AKG_CHANNEL1_SOUNDSTREAM_RELATIVEMODIFIERADDRESS:
PLY_AKG_CHANNEL1_GLIDEDIRECTION:
	ld a,0
    or a
    jr z,PLY_AKG_CHANNEL1_GLIDE_END
    ld (PLY_AKG_CHANNEL1_AFTERARPEGGIOPITCHVARIABLES+1),hl
    ld c,l
    ld b,h
    ex af,af'
    ld a,(PLY_AKG_CHANNEL1_TRACKNOTE+1)
    add a,a
    ld l,a
    ex af,af'
    ld h,0
    ld sp,PLY_AKG_PERIODTABLE
    add hl,sp
    ld sp,hl
    pop hl
    dec sp
    dec sp
    add hl,bc
PLY_AKG_CHANNEL1_GLIDETOREACH:
	ld bc,0
    rra 
    jr nc,PLY_AKG_CHANNEL1_GLIDEDOWNCHECK
    or a
    sbc hl,bc
    jr nc,PLY_AKG_CHANNEL1_AFTERARPEGGIOPITCHVARIABLES
    jr PLY_AKG_CHANNEL1_GLIDEOVER
PLY_AKG_CHANNEL1_GLIDEDOWNCHECK:
	sbc hl,bc
    jr c,PLY_AKG_CHANNEL1_AFTERARPEGGIOPITCHVARIABLES
PLY_AKG_CHANNEL1_GLIDEOVER:
	ld l,c
    ld h,b
    pop bc
    or a
    sbc hl,bc
    ld (PLY_AKG_CHANNEL1_PITCHTABLE_END+1),hl
    ld a,183
    ld (PLY_AKG_CHANNEL1_ISPITCH),a
    jr PLY_AKG_CHANNEL1_GLIDE_END
PLY_AKG_CHANNEL1_ARPEGGIOTABLESPEED:
	defb 0
PLY_AKG_CHANNEL1_ARPEGGIOBASESPEED:
	defb 0
PLY_AKG_CHANNEL1_ARPEGGIOTABLEBASE:
	defb 0
    defb 0
PLY_AKG_CHANNEL1_PITCHTABLESPEED:
	defb 0
PLY_AKG_CHANNEL1_PITCHBASESPEED:
	defb 0
PLY_AKG_CHANNEL1_PITCHTABLEBASE:
	defb 0
    defb 0
PLY_AKG_CHANNEL1_AFTERARPEGGIOPITCHVARIABLES:
PLY_AKG_CHANNEL1_GLIDE_BEFOREEND:
PLY_AKG_CHANNEL1_GLIDE_SAVEHL:
	ld hl,0
PLY_AKG_CHANNEL1_GLIDE_END:
	defb 221
    defb 77
PLY_AKG_CHANNEL1_PITCH_END:
	add hl,de
    ld (PLY_AKG_CHANNEL1_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS+1),hl
    ld a,c
    ld (PLY_AKG_CHANNEL1_GENERATEDCURRENTARPNOTE+1),a
defc PLY_AKG_CHANNEL2_INVERTEDVOLUMEINTEGER = 2
PLY_AKG_CHANNEL2_INVERTEDVOLUMEINTEGERANDDECIMAL:
	ld hl,0
PLY_AKG_CHANNEL2_ISVOLUMESLIDE:
	or a
    jr nc,PLY_AKG_CHANNEL2_VOLUMESLIDE_END
PLY_AKG_CHANNEL2_VOLUMESLIDEVALUE:
	ld de,0
    add hl,de
    bit 7,h
    jr z,PLY_AKG_CHANNEL2_VOLUMENOTOVERFLOW
    ld h,0
    jr PLY_AKG_CHANNEL2_VOLUMESETAGAIN
PLY_AKG_CHANNEL2_VOLUMENOTOVERFLOW:
	ld a,h
    cp 16
    jr c,PLY_AKG_CHANNEL2_VOLUMESETAGAIN
    ld h,15
PLY_AKG_CHANNEL2_VOLUMESETAGAIN:
	ld (PLY_AKG_CHANNEL2_INVERTEDVOLUMEINTEGERANDDECIMAL+1),hl
PLY_AKG_CHANNEL2_VOLUMESLIDE_END:
	ld a,h
    ld (PLY_AKG_CHANNEL2_GENERATEDCURRENTINVERTEDVOLUME+1),a
    ld c,0
PLY_AKG_CHANNEL2_ISARPEGGIOTABLE:
	or a
    jr nc,PLY_AKG_CHANNEL2_ARPEGGIOTABLE_END
PLY_AKG_CHANNEL2_ARPEGGIOTABLE:
	ld hl,0
    ld a,(hl)
    cp 128
    jr nz,PLY_AKG_CHANNEL2_ARPEGGIOTABLE_AFTERLOOPTEST
    inc hl
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    ld a,(hl)
PLY_AKG_CHANNEL2_ARPEGGIOTABLE_AFTERLOOPTEST:
	ld c,a
    ld a,(PLY_AKG_CHANNEL2_ARPEGGIOTABLESPEED)
    ld d,a
PLY_AKG_CHANNEL2_ARPEGGIOTABLECURRENTSTEP:
	ld a,0
    inc a
    cp d
    jr c,PLY_AKG_CHANNEL2_ARPEGGIOTABLE_BEFOREEND_SAVESTEP
    inc hl
    ld (PLY_AKG_CHANNEL2_ARPEGGIOTABLE+1),hl
    xor a
PLY_AKG_CHANNEL2_ARPEGGIOTABLE_BEFOREEND_SAVESTEP:
	ld (PLY_AKG_CHANNEL2_ARPEGGIOTABLECURRENTSTEP+1),a
PLY_AKG_CHANNEL2_ARPEGGIOTABLE_END:
	ld de,0
PLY_AKG_CHANNEL2_ISPITCHTABLE:
	or a
    jr nc,PLY_AKG_CHANNEL2_PITCHTABLE_END
PLY_AKG_CHANNEL2_PITCHTABLE:
	ld sp,0
    pop de
    pop hl
    ld a,(PLY_AKG_CHANNEL2_PITCHTABLESPEED)
    ld b,a
PLY_AKG_CHANNEL2_PITCHTABLECURRENTSTEP:
	ld a,0
    inc a
    cp b
    jr c,PLY_AKG_CHANNEL2_PITCHTABLE_BEFOREEND_SAVESTEP
    ld (PLY_AKG_CHANNEL2_PITCHTABLE+1),hl
    xor a
PLY_AKG_CHANNEL2_PITCHTABLE_BEFOREEND_SAVESTEP:
	ld (PLY_AKG_CHANNEL2_PITCHTABLECURRENTSTEP+1),a
PLY_AKG_CHANNEL2_PITCHTABLE_END:
PLY_AKG_CHANNEL2_PITCH:
	ld hl,0
PLY_AKG_CHANNEL2_ISPITCH:
	or a
    jr nc,PLY_AKG_CHANNEL2_PITCH_END
    defb 221
    defb 105
PLY_AKG_CHANNEL2_PITCHTRACK:
	ld bc,0
    or a
PLY_AKG_CHANNEL2_PITCHTRACKADDORSBC_16BITS:
	nop
    add hl,bc
PLY_AKG_CHANNEL2_PITCHTRACKDECIMALCOUNTER:
	ld a,0
defc PLY_AKG_CHANNEL2_PITCHTRACKDECIMALVALUE = 1
PLY_AKG_CHANNEL2_PITCHTRACKDECIMALINSTR:
	add a,0
    ld (PLY_AKG_CHANNEL2_PITCHTRACKDECIMALCOUNTER+1),a
    jr nc,PLY_AKG_CHANNEL2_PITCHNOCARRY
PLY_AKG_CHANNEL2_PITCHTRACKINTEGERADDORSUB:
	inc hl
PLY_AKG_CHANNEL2_PITCHNOCARRY:
	ld (PLY_AKG_CHANNEL2_PITCHTABLE_END+1),hl
PLY_AKG_CHANNEL2_SOUNDSTREAM_RELATIVEMODIFIERADDRESS:
PLY_AKG_CHANNEL2_GLIDEDIRECTION:
	ld a,0
    or a
    jr z,PLY_AKG_CHANNEL2_GLIDE_END
    ld (PLY_AKG_CHANNEL2_AFTERARPEGGIOPITCHVARIABLES+1),hl
    ld c,l
    ld b,h
    ex af,af'
    ld a,(PLY_AKG_CHANNEL2_TRACKNOTE+1)
    add a,a
    ld l,a
    ex af,af'
    ld h,0
    ld sp,PLY_AKG_PERIODTABLE
    add hl,sp
    ld sp,hl
    pop hl
    dec sp
    dec sp
    add hl,bc
PLY_AKG_CHANNEL2_GLIDETOREACH:
	ld bc,0
    rra 
    jr nc,PLY_AKG_CHANNEL2_GLIDEDOWNCHECK
    or a
    sbc hl,bc
    jr nc,PLY_AKG_CHANNEL2_AFTERARPEGGIOPITCHVARIABLES
    jr PLY_AKG_CHANNEL2_GLIDEOVER
PLY_AKG_CHANNEL2_GLIDEDOWNCHECK:
	sbc hl,bc
    jr c,PLY_AKG_CHANNEL2_AFTERARPEGGIOPITCHVARIABLES
PLY_AKG_CHANNEL2_GLIDEOVER:
	ld l,c
    ld h,b
    pop bc
    or a
    sbc hl,bc
    ld (PLY_AKG_CHANNEL2_PITCHTABLE_END+1),hl
    ld a,183
    ld (PLY_AKG_CHANNEL2_ISPITCH),a
    jr PLY_AKG_CHANNEL2_GLIDE_END
PLY_AKG_CHANNEL2_ARPEGGIOTABLESPEED:
	defb 0
PLY_AKG_CHANNEL2_ARPEGGIOBASESPEED:
	defb 0
PLY_AKG_CHANNEL2_ARPEGGIOTABLEBASE:
	defb 0
    defb 0
PLY_AKG_CHANNEL2_PITCHTABLESPEED:
	defb 0
PLY_AKG_CHANNEL2_PITCHBASESPEED:
	defb 0
PLY_AKG_CHANNEL2_PITCHTABLEBASE:
	defb 0
    defb 0
PLY_AKG_CHANNEL2_AFTERARPEGGIOPITCHVARIABLES:
PLY_AKG_CHANNEL2_GLIDE_BEFOREEND:
PLY_AKG_CHANNEL2_GLIDE_SAVEHL:
	ld hl,0
PLY_AKG_CHANNEL2_GLIDE_END:
	defb 221
    defb 77
PLY_AKG_CHANNEL2_PITCH_END:
	add hl,de
    ld (PLY_AKG_CHANNEL2_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS+1),hl
    ld a,c
    ld (PLY_AKG_CHANNEL2_GENERATEDCURRENTARPNOTE+1),a
defc PLY_AKG_CHANNEL3_INVERTEDVOLUMEINTEGER = 2
PLY_AKG_CHANNEL3_INVERTEDVOLUMEINTEGERANDDECIMAL:
	ld hl,0
PLY_AKG_CHANNEL3_ISVOLUMESLIDE:
	or a
    jr nc,PLY_AKG_CHANNEL3_VOLUMESLIDE_END
PLY_AKG_CHANNEL3_VOLUMESLIDEVALUE:
	ld de,0
    add hl,de
    bit 7,h
    jr z,PLY_AKG_CHANNEL3_VOLUMENOTOVERFLOW
    ld h,0
    jr PLY_AKG_CHANNEL3_VOLUMESETAGAIN
PLY_AKG_CHANNEL3_VOLUMENOTOVERFLOW:
	ld a,h
    cp 16
    jr c,PLY_AKG_CHANNEL3_VOLUMESETAGAIN
    ld h,15
PLY_AKG_CHANNEL3_VOLUMESETAGAIN:
	ld (PLY_AKG_CHANNEL3_INVERTEDVOLUMEINTEGERANDDECIMAL+1),hl
PLY_AKG_CHANNEL3_VOLUMESLIDE_END:
	ld a,h
    ld (PLY_AKG_CHANNEL3_GENERATEDCURRENTINVERTEDVOLUME+1),a
    ld c,0
PLY_AKG_CHANNEL3_ISARPEGGIOTABLE:
	or a
    jr nc,PLY_AKG_CHANNEL3_ARPEGGIOTABLE_END
PLY_AKG_CHANNEL3_ARPEGGIOTABLE:
	ld hl,0
    ld a,(hl)
    cp 128
    jr nz,PLY_AKG_CHANNEL3_ARPEGGIOTABLE_AFTERLOOPTEST
    inc hl
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    ld a,(hl)
PLY_AKG_CHANNEL3_ARPEGGIOTABLE_AFTERLOOPTEST:
	ld c,a
    ld a,(PLY_AKG_CHANNEL3_ARPEGGIOTABLESPEED)
    ld d,a
PLY_AKG_CHANNEL3_ARPEGGIOTABLECURRENTSTEP:
	ld a,0
    inc a
    cp d
    jr c,PLY_AKG_CHANNEL3_ARPEGGIOTABLE_BEFOREEND_SAVESTEP
    inc hl
    ld (PLY_AKG_CHANNEL3_ARPEGGIOTABLE+1),hl
    xor a
PLY_AKG_CHANNEL3_ARPEGGIOTABLE_BEFOREEND_SAVESTEP:
	ld (PLY_AKG_CHANNEL3_ARPEGGIOTABLECURRENTSTEP+1),a
PLY_AKG_CHANNEL3_ARPEGGIOTABLE_END:
	ld de,0
PLY_AKG_CHANNEL3_ISPITCHTABLE:
	or a
    jr nc,PLY_AKG_CHANNEL3_PITCHTABLE_END
PLY_AKG_CHANNEL3_PITCHTABLE:
	ld sp,0
    pop de
    pop hl
    ld a,(PLY_AKG_CHANNEL3_PITCHTABLESPEED)
    ld b,a
PLY_AKG_CHANNEL3_PITCHTABLECURRENTSTEP:
	ld a,0
    inc a
    cp b
    jr c,PLY_AKG_CHANNEL3_PITCHTABLE_BEFOREEND_SAVESTEP
    ld (PLY_AKG_CHANNEL3_PITCHTABLE+1),hl
    xor a
PLY_AKG_CHANNEL3_PITCHTABLE_BEFOREEND_SAVESTEP:
	ld (PLY_AKG_CHANNEL3_PITCHTABLECURRENTSTEP+1),a
PLY_AKG_CHANNEL3_PITCHTABLE_END:
PLY_AKG_CHANNEL3_PITCH:
	ld hl,0
PLY_AKG_CHANNEL3_ISPITCH:
	or a
    jr nc,PLY_AKG_CHANNEL3_PITCH_END
    defb 221
    defb 105
PLY_AKG_CHANNEL3_PITCHTRACK:
	ld bc,0
    or a
PLY_AKG_CHANNEL3_PITCHTRACKADDORSBC_16BITS:
	nop
    add hl,bc
PLY_AKG_CHANNEL3_PITCHTRACKDECIMALCOUNTER:
	ld a,0
defc PLY_AKG_CHANNEL3_PITCHTRACKDECIMALVALUE = 1
PLY_AKG_CHANNEL3_PITCHTRACKDECIMALINSTR:
	add a,0
    ld (PLY_AKG_CHANNEL3_PITCHTRACKDECIMALCOUNTER+1),a
    jr nc,PLY_AKG_CHANNEL3_PITCHNOCARRY
PLY_AKG_CHANNEL3_PITCHTRACKINTEGERADDORSUB:
	inc hl
PLY_AKG_CHANNEL3_PITCHNOCARRY:
	ld (PLY_AKG_CHANNEL3_PITCHTABLE_END+1),hl
PLY_AKG_CHANNEL3_SOUNDSTREAM_RELATIVEMODIFIERADDRESS:
PLY_AKG_CHANNEL3_GLIDEDIRECTION:
	ld a,0
    or a
    jr z,PLY_AKG_CHANNEL3_GLIDE_END
    ld (PLY_AKG_CHANNEL3_AFTERARPEGGIOPITCHVARIABLES+1),hl
    ld c,l
    ld b,h
    ex af,af'
    ld a,(PLY_AKG_CHANNEL3_TRACKNOTE+1)
    add a,a
    ld l,a
    ex af,af'
    ld h,0
    ld sp,PLY_AKG_PERIODTABLE
    add hl,sp
    ld sp,hl
    pop hl
    dec sp
    dec sp
    add hl,bc
PLY_AKG_CHANNEL3_GLIDETOREACH:
	ld bc,0
    rra 
    jr nc,PLY_AKG_CHANNEL3_GLIDEDOWNCHECK
    or a
    sbc hl,bc
    jr nc,PLY_AKG_CHANNEL3_AFTERARPEGGIOPITCHVARIABLES
    jr PLY_AKG_CHANNEL3_GLIDEOVER
PLY_AKG_CHANNEL3_GLIDEDOWNCHECK:
	sbc hl,bc
    jr c,PLY_AKG_CHANNEL3_AFTERARPEGGIOPITCHVARIABLES
PLY_AKG_CHANNEL3_GLIDEOVER:
	ld l,c
    ld h,b
    pop bc
    or a
    sbc hl,bc
    ld (PLY_AKG_CHANNEL3_PITCHTABLE_END+1),hl
    ld a,183
    ld (PLY_AKG_CHANNEL3_ISPITCH),a
    jr PLY_AKG_CHANNEL3_GLIDE_END
PLY_AKG_CHANNEL3_ARPEGGIOTABLESPEED:
	defb 0
PLY_AKG_CHANNEL3_ARPEGGIOBASESPEED:
	defb 0
PLY_AKG_CHANNEL3_ARPEGGIOTABLEBASE:
	defb 0
    defb 0
PLY_AKG_CHANNEL3_PITCHTABLESPEED:
	defb 0
PLY_AKG_CHANNEL3_PITCHBASESPEED:
	defb 0
PLY_AKG_CHANNEL3_PITCHTABLEBASE:
	defb 0
    defb 0
PLY_AKG_CHANNEL3_AFTERARPEGGIOPITCHVARIABLES:
PLY_AKG_CHANNEL3_GLIDE_BEFOREEND:
PLY_AKG_CHANNEL3_GLIDE_SAVEHL:
	ld hl,0
PLY_AKG_CHANNEL3_GLIDE_END:
	defb 221
    defb 77
PLY_AKG_CHANNEL3_PITCH_END:
	add hl,de
    ld (PLY_AKG_CHANNEL3_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS+1),hl
    ld a,c
    ld (PLY_AKG_CHANNEL3_GENERATEDCURRENTARPNOTE+1),a
    ld sp,(PLY_AKG_PSGREG13_END+1)
PLY_AKG_CHANNEL1_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS:
PLY_AKG_CHANNEL1_GENERATEDCURRENTPITCH:
	ld hl,0
PLY_AKG_CHANNEL1_TRACKNOTE:
	ld a,0
PLY_AKG_CHANNEL1_GENERATEDCURRENTARPNOTE:
	add a,0
    ld e,a
    ld d,0
    exx
PLY_AKG_CHANNEL1_INSTRUMENTSTEP:
	defb 253
    defb 46
    defb 0
PLY_AKG_CHANNEL1_PTINSTRUMENT:
	ld hl,0
PLY_AKG_CHANNEL1_GENERATEDCURRENTINVERTEDVOLUME:
	ld de,57359
    call PLY_AKG_READINSTRUMENTCELL
    defb 253
    defb 125
    inc a
PLY_AKG_CHANNEL1_INSTRUMENTSPEED:
	cp 0
    jr c,PLY_AKG_CHANNEL1_SETINSTRUMENTSTEP
    ld (PLY_AKG_CHANNEL1_PTINSTRUMENT+1),hl
    xor a
PLY_AKG_CHANNEL1_SETINSTRUMENTSTEP:
	ld (PLY_AKG_CHANNEL1_INSTRUMENTSTEP+2),a
    ld a,e
    ld (PLY_AKG_PSGREG8),a
    srl d
    exx
    ld (PLY_AKG_PSGREG01_INSTR+1),hl
PLY_AKG_CHANNEL2_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS:
PLY_AKG_CHANNEL2_GENERATEDCURRENTPITCH:
	ld hl,0
PLY_AKG_CHANNEL2_TRACKNOTE:
	ld a,0
PLY_AKG_CHANNEL2_GENERATEDCURRENTARPNOTE:
	add a,0
    ld e,a
    ld d,0
    exx
PLY_AKG_CHANNEL2_INSTRUMENTSTEP:
	defb 253
    defb 46
    defb 0
PLY_AKG_CHANNEL2_PTINSTRUMENT:
	ld hl,0
PLY_AKG_CHANNEL2_GENERATEDCURRENTINVERTEDVOLUME:
	ld e,15
    nop
    call PLY_AKG_READINSTRUMENTCELL
    defb 253
    defb 125
    inc a
PLY_AKG_CHANNEL2_INSTRUMENTSPEED:
	cp 0
    jr c,PLY_AKG_CHANNEL2_SETINSTRUMENTSTEP
    ld (PLY_AKG_CHANNEL2_PTINSTRUMENT+1),hl
    xor a
PLY_AKG_CHANNEL2_SETINSTRUMENTSTEP:
	ld (PLY_AKG_CHANNEL2_INSTRUMENTSTEP+2),a
    ld a,e
    ld (PLY_AKG_PSGREG9),a
    srl d
    exx
    ld (PLY_AKG_PSGREG23_INSTR+1),hl
PLY_AKG_CHANNEL3_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS:
PLY_AKG_CHANNEL3_GENERATEDCURRENTPITCH:
	ld hl,0
PLY_AKG_CHANNEL3_TRACKNOTE:
	ld a,0
PLY_AKG_CHANNEL3_GENERATEDCURRENTARPNOTE:
	add a,0
    ld e,a
    ld d,0
    exx
PLY_AKG_CHANNEL3_INSTRUMENTSTEP:
	defb 253
    defb 46
    defb 0
PLY_AKG_CHANNEL3_PTINSTRUMENT:
	ld hl,0
PLY_AKG_CHANNEL3_GENERATEDCURRENTINVERTEDVOLUME:
	ld e,15
    nop
    call PLY_AKG_READINSTRUMENTCELL
    defb 253
    defb 125
    inc a
PLY_AKG_CHANNEL3_INSTRUMENTSPEED:
	cp 0
    jr c,PLY_AKG_CHANNEL3_SETINSTRUMENTSTEP
    ld (PLY_AKG_CHANNEL3_PTINSTRUMENT+1),hl
    xor a
PLY_AKG_CHANNEL3_SETINSTRUMENTSTEP:
	ld (PLY_AKG_CHANNEL3_INSTRUMENTSTEP+2),a
    ld a,e
    ld (PLY_AKG_PSGREG10),a
    ld a,d
    exx
    ld (PLY_AKG_PSGREG45_INSTR+1),hl
    call PLY_AKG_PLAYSOUNDEFFECTSSTREAM
PLY_AKG_SENDPSGREGISTERS:
	ld bc,63104
    ld e,192
    out (c),e
    exx
    ld bc,62465
PLY_AKG_PSGREG01_INSTR:
	ld hl,0
    defb 237
    defb 113
    exx
    defb 237
    defb 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
PLY_AKG_PSGREG23_INSTR:
	ld hl,0
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
PLY_AKG_PSGREG45_INSTR:
	ld hl,0
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
defc PLY_AKG_PSGREG6 = 1
defc PLY_AKG_PSGREG8 = 2
PLY_AKG_PSGREG6_8_INSTR:
	ld hl,0
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),a
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
defc PLY_AKG_PSGREG9 = 1
defc PLY_AKG_PSGREG10 = 2
PLY_AKG_PSGREG9_10_INSTR:
	ld hl,0
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
PLY_AKG_PSGHARDWAREPERIOD_INSTR:
	ld hl,0
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),l
    exx
    out (c),c
    out (c),e
    exx
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),h
    exx
    out (c),c
    out (c),e
    exx
PLY_AKG_PSGREG13_INSTR:
	ld a,0
PLY_AKG_PSGREG13_OLDVALUE:
	cp 255
    jr z,PLY_AKG_PSGREG13_END
    ld (PLY_AKG_PSGREG13_OLDVALUE+1),a
    inc c
    out (c),c
    exx
    defb 237
    defb 113
    exx
    out (c),a
    exx
    out (c),c
    out (c),e
PLY_AKG_PSGREG13_END:
PLY_AKG_SAVESP:
	ld sp,0
    ret 
PLY_AKG_CHANNEL1_MAYBEEFFECTS:
	ld (PLY_AKG_SPEEDTRACK_END+1),a
    bit 6,c
    jp z,PLY_AKG_CHANNEL1_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL1_READEFFECTS:
	ld iy,PLY_AKG_CHANNEL1_SOUNDSTREAM_RELATIVEMODIFIERADDRESS
    ld ix,PLY_AKG_CHANNEL1_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS
    ld de,PLY_AKG_CHANNEL1_BEFOREEND_STORECELLPOINTER
    jr PLY_AKG_CHANNEL3_READEFFECTSEND
PLY_AKG_CHANNEL1_READEFFECTSEND:
PLY_AKG_CHANNEL2_MAYBEEFFECTS:
	ld (PLY_AKG_CHANNEL1_READCELLEND+1),a
    bit 6,c
    jp z,PLY_AKG_CHANNEL2_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL2_READEFFECTS:
	ld iy,PLY_AKG_CHANNEL2_SOUNDSTREAM_RELATIVEMODIFIERADDRESS
    ld ix,PLY_AKG_CHANNEL2_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS
    ld de,PLY_AKG_CHANNEL2_BEFOREEND_STORECELLPOINTER
    jr PLY_AKG_CHANNEL3_READEFFECTSEND
PLY_AKG_CHANNEL2_READEFFECTSEND:
PLY_AKG_CHANNEL3_MAYBEEFFECTS:
	ld (PLY_AKG_CHANNEL2_READCELLEND+1),a
    bit 6,c
    jp z,PLY_AKG_CHANNEL3_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL3_READEFFECTS:
	ld iy,PLY_AKG_CHANNEL3_SOUNDSTREAM_RELATIVEMODIFIERADDRESS
    ld ix,PLY_AKG_CHANNEL3_PLAYINSTRUMENT_RELATIVEMODIFIERADDRESS
    ld de,PLY_AKG_CHANNEL3_BEFOREEND_STORECELLPOINTER
PLY_AKG_CHANNEL3_READEFFECTSEND:
PLY_AKG_CHANNEL_READEFFECTS:
	ld (PLY_AKG_CHANNEL_READEFFECTS_ENDJUMP+1),de
    ex de,hl
    ld a,(de)
    inc de
    sla a
    jr c,PLY_AKG_CHANNEL_READEFFECTS_RELATIVEADDRESS
    exx
    ld l,a
    ld h,0
PLY_AKG_CHANNEL_READEFFECTS_EFFECTBLOCKS1:
	ld de,0
    add hl,de
    ld e,(hl)
    inc hl
    ld d,(hl)
PLY_AKG_CHANNEL_RE_EFFECTADDRESSKNOWN:
	ld a,(de)
    inc de
    ld (PLY_AKG_CHANNEL_RE_EFFECTRETURN+1),a
    and 254
    ld l,a
    ld h,0
    ld sp,PLY_AKG_EFFECTTABLE
    add hl,sp
    ld sp,hl
    ret 
PLY_AKG_CHANNEL_RE_EFFECTRETURN:
PLY_AKG_CHANNEL_RE_READNEXTEFFECTINBLOCK:
	ld a,0
    rra 
    jr c,PLY_AKG_CHANNEL_RE_EFFECTADDRESSKNOWN
    exx
    ex de,hl
PLY_AKG_CHANNEL_READEFFECTS_ENDJUMP:
	jp 0
PLY_AKG_CHANNEL_READEFFECTS_RELATIVEADDRESS:
	srl a
    exx
    ld h,a
    exx
    ld a,(de)
    inc de
    exx
    ld l,a
PLY_AKG_CHANNEL_READEFFECTS_EFFECTBLOCKS2:
	ld de,0
    add hl,de
    jr PLY_AKG_CHANNEL_RE_EFFECTADDRESSKNOWN
PLY_AKG_READINSTRUMENTCELL:
	ld a,(hl)
    inc hl
    ld b,a
    rra 
    jp c,PLY_AKG_S_OR_H_OR_SAH_OR_ENDWITHLOOP
    rra 
    jr c,PLY_AKG_STH_OR_ENDWITHOUTLOOP
    rra 
PLY_AKG_NOSOFTNOHARD:
	and 15
    sub e
    jr nc,PLY_AKG_NOSOFTNOHARD+6
    xor a
    ld e,a
    rl b
    jr nc,PLY_AKG_NSNH_NONOISE
    ld a,(hl)
    inc hl
    ld (PLY_AKG_PSGREG6),a
    set 2,d
    res 5,d
    ret 
PLY_AKG_NSNH_NONOISE:
	set 2,d
    ret 
PLY_AKG_SOFT:
	and 15
    sub e
    jr nc,PLY_AKG_SOFTONLY_HARDONLY_TESTSIMPLE_COMMON-1
    xor a
    ld e,a
PLY_AKG_SOFTONLY_HARDONLY_TESTSIMPLE_COMMON:
	rl b
    jr nc,PLY_AKG_S_NOTSIMPLE
    ld c,0
    jr PLY_AKG_S_AFTERSIMPLETEST
PLY_AKG_S_NOTSIMPLE:
	ld b,(hl)
    ld c,b
    inc hl
PLY_AKG_S_AFTERSIMPLETEST:
	call PLY_AKG_S_OR_H_CHECKIFSIMPLEFIRST_CALCULATEPERIOD
    ld a,c
    and 31
    ret z
    ld (PLY_AKG_PSGREG6),a
    res 5,d
    ret 
PLY_AKG_ENDWITHOUTLOOP:
PLY_AKG_EMPTYINSTRUMENTDATAPT:
	ld hl,0
    inc hl
    xor a
    ld b,a
    jr PLY_AKG_NOSOFTNOHARD
PLY_AKG_STH_OR_ENDWITHOUTLOOP:
	rra 
    jr c,PLY_AKG_ENDWITHOUTLOOP
    call PLY_AKG_STOH_HTOS_SANDH_COMMON
    ld (PLY_AKG_SH_JUMPRATIO+1),a
    exx
    ld e,l
    ld d,h
PLY_AKG_SH_JUMPRATIO:
	jr PLY_AKG_SH_JUMPRATIO+2
    srl h
    rr l
    srl h
    rr l
    srl h
    rr l
    srl h
    rr l
    srl h
    rr l
    srl h
    rr l
    srl h
    rr l
    jr nc,PLY_AKG_SH_JUMPRATIOEND
    inc hl
PLY_AKG_SH_JUMPRATIOEND:
	ld (PLY_AKG_PSGHARDWAREPERIOD_INSTR+1),hl
    ex de,hl
    exx
    ret 
PLY_AKG_S_OR_H_OR_SAH_OR_ENDWITHLOOP:
	rra 
    jr c,PLY_AKG_H_OR_ENDWITHLOOP
    rra 
    jp nc,PLY_AKG_SOFT
PLY_AKG_H_OR_ENDWITHLOOP:
PLY_AKG_ENDWITHLOOP:
	ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    jp PLY_AKG_READINSTRUMENTCELL
PLY_AKG_S_OR_H_CHECKIFSIMPLEFIRST_CALCULATEPERIOD:
	jr nc,PLY_AKG_S_OR_H_NEXTBYTE
    exx
    ex de,hl
    add hl,hl
    ld bc,PLY_AKG_PERIODTABLE
    add hl,bc
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    add hl,de
    exx
    rl b
    rl b
    rl b
    ret 
PLY_AKG_S_OR_H_NEXTBYTE:
	rl b
    jr c,PLY_AKG_S_OR_H_FORCEDPERIOD
    rl b
    jr nc,PLY_AKG_S_OR_H_AFTERARPEGGIO
    ld a,(hl)
    inc hl
    exx
    add a,e
    ld e,a
    exx
PLY_AKG_S_OR_H_AFTERARPEGGIO:
	rl b
    exx
    ex de,hl
    add hl,hl
    ld bc,PLY_AKG_PERIODTABLE
    add hl,bc
    ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    add hl,de
    exx
    ret 
PLY_AKG_S_OR_H_FORCEDPERIOD:
	ld a,(hl)
    inc hl
    exx
    ld l,a
    exx
    ld a,(hl)
    inc hl
    exx
    ld h,a
    exx
    rl b
    rl b
    ret 
PLY_AKG_STOH_HTOS_SANDH_COMMON:
	ld e,16
    rra 
    and 7
    add a,8
    ld (PLY_AKG_PSGREG13_INSTR+1),a
    rl b
    ld c,(hl)
    ld b,c
    inc hl
    rl b
    call PLY_AKG_S_OR_H_CHECKIFSIMPLEFIRST_CALCULATEPERIOD
    ld a,c
    rla 
    rla 
    and 28
    ret 
PLY_AKG_EFFECTTABLE:
	defw PLY_AKG_START
    defw PLY_AKG_START
    defw PLY_AKG_EFFECT_VOLUME
    defw PLY_AKG_EFFECT_ARPEGGIOTABLE
    defw PLY_AKG_EFFECT_ARPEGGIOTABLESTOP
    defw PLY_AKG_EFFECT_PITCHTABLE
    defw PLY_AKG_EFFECT_PITCHTABLESTOP
    defw PLY_AKG_EFFECT_VOLUMESLIDE
    defw PLY_AKG_EFFECT_VOLUMESLIDESTOP
    defw PLY_AKG_EFFECT_PITCHUP
    defw PLY_AKG_EFFECT_PITCHDOWN
    defw PLY_AKG_EFFECT_PITCHSTOP
    defw PLY_AKG_EFFECT_GLIDEWITHNOTE
    defw PLY_AKG_EFFECT_GLIDE_READSPEED
    defw PLY_AKG_START
    defw PLY_AKG_START
    defw PLY_AKG_START
PLY_AKG_EFFECT_VOLUME:
	ld a,(de)
    inc de
    ld (iy-123),a
    ld (iy-122),183
    jp PLY_AKG_CHANNEL_RE_EFFECTRETURN
PLY_AKG_EFFECT_ARPEGGIOTABLE:
	ld a,(de)
    inc de
    ld l,a
    ld h,0
    add hl,hl
PLY_AKG_ARPEGGIOSTABLE:
	ld bc,0
    add hl,bc
    ld c,(hl)
    inc hl
    ld b,(hl)
    inc hl
    ld a,(bc)
    inc bc
    ld (iy+61),a
    ld (iy+62),a
    ld (iy-87),c
    ld (iy-86),b
    ld (iy+63),c
    ld (iy+64),b
    ld (iy-91),55
    xor a
    ld (iy-68),a
    jp PLY_AKG_CHANNEL_RE_EFFECTRETURN
PLY_AKG_EFFECT_ARPEGGIOTABLESTOP:
	ld (iy-91),183
    jp PLY_AKG_CHANNEL_RE_EFFECTRETURN
PLY_AKG_EFFECT_PITCHTABLE:
	ld a,(de)
    inc de
    ld l,a
    ld h,0
    add hl,hl
PLY_AKG_PITCHESTABLE:
	ld bc,0
    add hl,bc
    ld c,(hl)
    inc hl
    ld b,(hl)
    inc hl
    ld a,(bc)
    inc bc
    ld (iy+65),a
    ld (iy+66),a
    ld (iy-48),c
    ld (iy-47),b
    ld (iy+67),c
    ld (iy+68),b
    ld (iy-52),55
    xor a
    ld (iy-39),a
    jp PLY_AKG_CHANNEL_RE_EFFECTRETURN
PLY_AKG_EFFECT_PITCHTABLESTOP:
	ld (iy-52),183
    jp PLY_AKG_CHANNEL_RE_EFFECTRETURN
PLY_AKG_EFFECT_VOLUMESLIDE:
	ld a,(de)
    inc de
    ld (iy-118),a
    ld a,(de)
    inc de
    ld (iy-117),a
    ld (iy-122),55
    jp PLY_AKG_CHANNEL_RE_EFFECTRETURN
PLY_AKG_EFFECT_VOLUMESLIDESTOP:
	ld (iy-122),183
    jp PLY_AKG_CHANNEL_RE_EFFECTRETURN
PLY_AKG_EFFECT_PITCHDOWN:
	ld (iy-15),0
    ld (iy-14),9
    ld (iy-11),198
    ld (iy-4),35
PLY_AKG_EFFECT_PITCHUPDOWN_COMMON:
	ld (iy-24),55
    ld (iy+1),0
    ld a,(de)
    inc de
    ld (iy-10),a
    ld a,(de)
    inc de
    ld (iy-18),a
    jp PLY_AKG_CHANNEL_RE_EFFECTRETURN
PLY_AKG_EFFECT_PITCHUP:
	ld (iy-15),237
    ld (iy-14),66
    ld (iy-11),214
    ld (iy-4),43
    jr PLY_AKG_EFFECT_PITCHUPDOWN_COMMON
PLY_AKG_EFFECT_PITCHSTOP:
	ld (iy-24),183
    jp PLY_AKG_CHANNEL_RE_EFFECTRETURN
PLY_AKG_EFFECT_GLIDEWITHNOTE:
	ld a,(de)
    inc de
    ld (PLY_AKG_EFFECT_GLIDEWITHNOTESAVEDE+1),de
    add a,a
    ld l,a
    ld h,0
    ld bc,PLY_AKG_PERIODTABLE
    add hl,bc
    ld sp,hl
    pop de
    ld (iy+29),e
    ld (iy+30),d
    ld a,(ix+4)
    add a,a
    ld l,a
    ld h,0
    add hl,bc
    ld sp,hl
    pop hl
    ld c,(iy-26)
    ld b,(iy-25)
    add hl,bc
    or a
    sbc hl,de
PLY_AKG_EFFECT_GLIDEWITHNOTESAVEDE:
	ld de,0
    jr c,PLY_AKG_EFFECT_GLIDE_PITCHDOWN
    ld (iy+1),1
    ld (iy-15),237
    ld (iy-14),66
    ld (iy-11),214
    ld (iy-4),43
PLY_AKG_EFFECT_GLIDE_READSPEED:
PLY_AKG_EFFECT_GLIDESPEED:
	ld a,(de)
    inc de
    ld (iy-10),a
    ld a,(de)
    inc de
    ld (iy-18),a
    ld a,55
    ld (iy-24),a
    jp PLY_AKG_CHANNEL_RE_EFFECTRETURN
PLY_AKG_EFFECT_GLIDE_PITCHDOWN:
	ld (iy+1),2
    ld (iy-15),0
    ld (iy-14),9
    ld (iy-11),198
    ld (iy-4),35
    jr PLY_AKG_EFFECT_GLIDE_READSPEED
PLY_AKG_PERIODTABLE:
	defw 3822
    defw 3608
    defw 3405
    defw 3214
    defw 3034
    defw 2863
    defw 2703
    defw 2551
    defw 2408
    defw 2273
    defw 2145
    defw 2025
    defw 1911
    defw 1804
    defw 1703
    defw 1607
    defw 1517
    defw 1432
    defw 1351
    defw 1276
    defw 1204
    defw 1136
    defw 1073
    defw 1012
    defw 956
    defw 902
    defw 851
    defw 804
    defw 758
    defw 716
    defw 676
    defw 638
    defw 602
    defw 568
    defw 536
    defw 506
    defw 478
    defw 451
    defw 426
    defw 402
    defw 379
    defw 358
    defw 338
    defw 319
    defw 301
    defw 284
    defw 268
    defw 253
    defw 239
    defw 225
    defw 213
    defw 201
    defw 190
    defw 179
    defw 169
    defw 159
    defw 150
    defw 142
    defw 134
    defw 127
    defw 119
    defw 113
    defw 106
    defw 100
    defw 95
    defw 89
    defw 84
    defw 80
    defw 75
    defw 71
    defw 67
    defw 63
    defw 60
    defw 56
    defw 53
    defw 50
    defw 47
    defw 45
    defw 42
    defw 40
    defw 38
    defw 36
    defw 34
    defw 32
    defw 30
    defw 28
    defw 27
    defw 25
    defw 24
    defw 22
    defw 21
    defw 20
    defw 19
    defw 18
    defw 17
    defw 16
    defw 15
    defw 14
    defw 13
    defw 13
    defw 12
    defw 11
    defw 11
    defw 10
    defw 9
    defw 9
    defw 8
    defw 8
    defw 7
    defw 7
    defw 7
    defw 6
    defw 6
    defw 6
    defw 5
    defw 5
    defw 5
    defw 4
    defw 4
    defw 4
    defw 4
    defw 4
    defw 3
    defw 3
    defw 3
    defw 3
    defw 3
    defw 2
PLY_AKG_PERIODTABLE_END:
PLY_AKG_END:
_SONG:
JUSTADDCREAM_START:
	defb 65
    defb 84
    defb 50
    defb 48
    defw JUSTADDCREAM_ARPEGGIOTABLE
    defw JUSTADDCREAM_PITCHTABLE
    defw JUSTADDCREAM_INSTRUMENTTABLE
    defw JUSTADDCREAM_EFFECTBLOCKTABLE
    defw JUSTADDCREAM_SUBSONG0_START
JUSTADDCREAM_ARPEGGIOTABLE:
	defw JUSTADDCREAM_ARPEGGIO1
    defw JUSTADDCREAM_ARPEGGIO2
    defw JUSTADDCREAM_ARPEGGIO3
JUSTADDCREAM_ARPEGGIO1:
	defb 2
    defb 7
    defb 4
    defb 0
    defb 128
    defw JUSTADDCREAM_ARPEGGIO1+1
JUSTADDCREAM_ARPEGGIO2:
	defb 2
    defb 16
    defb 12
    defb 7
    defb 128
    defw JUSTADDCREAM_ARPEGGIO2+1
JUSTADDCREAM_ARPEGGIO3:
	defb 2
    defb 12
    defb 7
    defb 4
    defb 128
    defw JUSTADDCREAM_ARPEGGIO3+1
JUSTADDCREAM_PITCHTABLE:
	defw JUSTADDCREAM_PITCH1
JUSTADDCREAM_PITCH1:
	defb 1
    defb 255
    defb 255
JUSTADDCREAM_PITCH1_GOTONEXTFORLINE0:
	defw JUSTADDCREAM_PITCH1_GOTONEXTFORLINE0+2
    defb 254
    defb 255
JUSTADDCREAM_PITCH1_GOTONEXTFORLINE1:
	defw JUSTADDCREAM_PITCH1_GOTONEXTFORLINE1+2
    defb 253
    defb 255
JUSTADDCREAM_PITCH1_GOTONEXTFORLINE2:
	defw JUSTADDCREAM_PITCH1_GOTONEXTFORLINE2+2
    defb 254
    defb 255
JUSTADDCREAM_PITCH1_GOTONEXTFORLINE3:
	defw JUSTADDCREAM_PITCH1_GOTONEXTFORLINE3+2
    defb 255
    defb 255
JUSTADDCREAM_PITCH1_GOTONEXTFORLINE4:
	defw JUSTADDCREAM_PITCH1_GOTONEXTFORLINE4+2
    defb 1
    defb 0
JUSTADDCREAM_PITCH1_GOTONEXTFORLINE5:
	defw JUSTADDCREAM_PITCH1_GOTONEXTFORLINE5+2
    defb 2
    defb 0
JUSTADDCREAM_PITCH1_GOTONEXTFORLINE6:
	defw JUSTADDCREAM_PITCH1_GOTONEXTFORLINE6+2
    defb 3
    defb 0
JUSTADDCREAM_PITCH1_GOTONEXTFORLINE7:
	defw JUSTADDCREAM_PITCH1_GOTONEXTFORLINE7+2
    defb 2
    defb 0
    defw JUSTADDCREAM_PITCH1+1
JUSTADDCREAM_INSTRUMENTTABLE:
	defw JUSTADDCREAM_EMPTYINSTRUMENT
    defw JUSTADDCREAM_INSTRUMENT1
    defw JUSTADDCREAM_INSTRUMENT2
    defw JUSTADDCREAM_INSTRUMENT3
    defw JUSTADDCREAM_INSTRUMENT4
    defw JUSTADDCREAM_INSTRUMENT5
    defw JUSTADDCREAM_INSTRUMENT6
    defw JUSTADDCREAM_INSTRUMENT7
    defw JUSTADDCREAM_INSTRUMENT8
    defw JUSTADDCREAM_INSTRUMENT9
    defw JUSTADDCREAM_INSTRUMENT10
    defw JUSTADDCREAM_INSTRUMENT11
JUSTADDCREAM_EMPTYINSTRUMENT:
	defb 0
JUSTADDCREAM_EMPTYINSTRUMENT_LOOP:
	defb 0
    defb 6
JUSTADDCREAM_INSTRUMENT1:
	defb 1
    defb 105
    defb 159
    defb 188
    defb 3
    defb 121
    defb 128
    defb 244
    defb 3
    defb 121
    defb 128
    defb 252
    defb 4
    defb 121
    defb 128
    defb 237
    defb 5
    defb 105
    defb 128
    defb 104
    defb 9
    defb 6
JUSTADDCREAM_INSTRUMENT2:
	defb 1
    defb 121
    defb 145
    defb 170
    defb 1
    defb 121
    defb 128
    defb 24
    defb 2
    defb 121
    defb 128
    defb 126
    defb 2
    defb 121
    defb 128
    defb 204
    defb 2
    defb 232
    defb 13
    defb 216
    defb 13
    defb 6
JUSTADDCREAM_INSTRUMENT3:
	defb 1
    defb 2
    defb 130
    defb 2
    defb 130
    defb 233
    defb 225
    defb 217
    defb 217
JUSTADDCREAM_INSTRUMENT3_LOOP:
	defb 217
    defb 217
    defb 7
    defw JUSTADDCREAM_INSTRUMENT3_LOOP
JUSTADDCREAM_INSTRUMENT4:
	defb 1
    defb 225
    defb 217
    defb 209
JUSTADDCREAM_INSTRUMENT4_LOOP:
	defb 201
    defb 7
    defw JUSTADDCREAM_INSTRUMENT4_LOOP
JUSTADDCREAM_INSTRUMENT5:
	defb 1
    defb 105
    defb 159
    defb 188
    defb 3
    defb 121
    defb 128
    defb 244
    defb 3
    defb 121
    defb 128
    defb 252
    defb 4
    defb 121
    defb 128
    defb 237
    defb 5
JUSTADDCREAM_INSTRUMENT5_LOOP:
	defb 217
    defb 7
    defw JUSTADDCREAM_INSTRUMENT5_LOOP
JUSTADDCREAM_INSTRUMENT6:
	defb 1
    defb 113
    defb 145
    defb 170
    defb 1
    defb 113
    defb 128
    defb 24
    defb 2
    defb 113
    defb 128
    defb 126
    defb 2
    defb 113
    defb 128
    defb 204
    defb 2
    defb 224
    defb 13
JUSTADDCREAM_INSTRUMENT6_LOOP:
	defb 217
    defb 7
    defw JUSTADDCREAM_INSTRUMENT6_LOOP
JUSTADDCREAM_INSTRUMENT7:
	defb 1
    defb 241
    defb 233
    defb 225
JUSTADDCREAM_INSTRUMENT7_LOOP:
	defb 217
    defb 7
    defw JUSTADDCREAM_INSTRUMENT7_LOOP
JUSTADDCREAM_INSTRUMENT8:
	defb 1
JUSTADDCREAM_INSTRUMENT8_LOOP:
	defb 193
    defb 7
    defw JUSTADDCREAM_INSTRUMENT8_LOOP
JUSTADDCREAM_INSTRUMENT9:
	defb 1
    defb 73
    defb 64
    defb 12
    defb 65
    defb 64
    defb 12
    defb 185
JUSTADDCREAM_INSTRUMENT9_LOOP:
	defb 177
    defb 49
    defb 64
    defb 12
    defb 49
    defb 64
    defb 12
    defb 177
    defb 7
    defw JUSTADDCREAM_INSTRUMENT9_LOOP
JUSTADDCREAM_INSTRUMENT10:
	defb 1
    defb 49
    defb 64
    defb 12
    defb 41
    defb 64
    defb 12
    defb 161
JUSTADDCREAM_INSTRUMENT10_LOOP:
	defb 153
    defb 25
    defb 64
    defb 12
    defb 25
    defb 64
    defb 12
    defb 153
    defb 7
    defw JUSTADDCREAM_INSTRUMENT10_LOOP
JUSTADDCREAM_INSTRUMENT11:
	defb 1
    defb 41
    defb 64
    defb 12
    defb 33
    defb 64
    defb 12
    defb 153
JUSTADDCREAM_INSTRUMENT11_LOOP:
	defb 145
    defb 17
    defb 64
    defb 12
    defb 17
    defb 64
    defb 12
    defb 145
    defb 7
    defw JUSTADDCREAM_INSTRUMENT11_LOOP
JUSTADDCREAM_EFFECTBLOCKTABLE:
	defw JUSTADDCREAM_EFFECTBLOCK_P4P0
    defw JUSTADDCREAM_EFFECTBLOCK_P14P64P0
    defw JUSTADDCREAM_EFFECTBLOCK_P4P1
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P14P64P0
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P6P2
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P10P0
    defw JUSTADDCREAM_EFFECTBLOCK_P15P112P0P12
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P6P1
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P6P0
    defw JUSTADDCREAM_EFFECTBLOCK_P15P64P0P6P1
    defw JUSTADDCREAM_EFFECTBLOCK_P6P1
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P14P112P0
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P14P160P0
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P15P64P0P6P0
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P15P64P0P6P2
    defw JUSTADDCREAM_EFFECTBLOCK_P14P160P0
    defw JUSTADDCREAM_EFFECTBLOCK_P10P0
    defw JUSTADDCREAM_EFFECTBLOCK_P15P64P0P6P0
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P13P18P0P1
    defw JUSTADDCREAM_EFFECTBLOCK_P20P0P5
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P15P112P0P12
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P18P0P2
    defw JUSTADDCREAM_EFFECTBLOCK_P4P2
    defw JUSTADDCREAM_EFFECTBLOCK_P15P64P0P20P0P16
    defw JUSTADDCREAM_EFFECTBLOCK_P24P64P0P1
    defw JUSTADDCREAM_EFFECTBLOCK_P24P60P0P2
    defw JUSTADDCREAM_EFFECTBLOCK_P15P64P0P6P2
    defw JUSTADDCREAM_EFFECTBLOCK_P6P2
    defw JUSTADDCREAM_EFFECTBLOCK_P5P14P15P128P255P13P6P1
    defw JUSTADDCREAM_EFFECTBLOCK_P6P0
    defw JUSTADDCREAM_EFFECTBLOCK_P24P59P128P1
    defw JUSTADDCREAM_EFFECTBLOCK_P13P18P128P1
    defw JUSTADDCREAM_EFFECTBLOCK_P24P57P0P3
    defw JUSTADDCREAM_EFFECTBLOCK_P15P8P0P20P0P6
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P8
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P18P0P12
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P18P128P1
    defw JUSTADDCREAM_EFFECTBLOCK_P4P3
    defw JUSTADDCREAM_EFFECTBLOCK_P24P23P0P12
    defw JUSTADDCREAM_EFFECTBLOCK_P24P48P128P1
    defw JUSTADDCREAM_EFFECTBLOCK_P5P0P13P8
    defw JUSTADDCREAM_EFFECTBLOCK_P14P32P0
    defw JUSTADDCREAM_EFFECTBLOCK_P14P8P0
    defw JUSTADDCREAM_EFFECTBLOCK_P14P112P0
    defw JUSTADDCREAM_EFFECTBLOCK_P12
    defw JUSTADDCREAM_EFFECTBLOCK_P20P0P1
    defw JUSTADDCREAM_EFFECTBLOCK_P4P4
    defw JUSTADDCREAM_EFFECTBLOCK_P4P5
JUSTADDCREAM_EFFECTBLOCK_P12:
	defb 12
JUSTADDCREAM_EFFECTBLOCK_P4P0:
	defb 4
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P4P1:
	defb 4
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P4P2:
	defb 4
    defb 2
JUSTADDCREAM_EFFECTBLOCK_P4P3:
	defb 4
    defb 3
JUSTADDCREAM_EFFECTBLOCK_P4P4:
	defb 4
    defb 4
JUSTADDCREAM_EFFECTBLOCK_P4P5:
	defb 4
    defb 5
JUSTADDCREAM_EFFECTBLOCK_P6P0:
	defb 6
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P6P1:
	defb 6
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P6P2:
	defb 6
    defb 2
JUSTADDCREAM_EFFECTBLOCK_P5P0P8:
	defb 5
    defb 0
    defb 8
JUSTADDCREAM_EFFECTBLOCK_P24P60P0P2:
	defb 24
    defb 60
    defb 0
    defb 2
JUSTADDCREAM_EFFECTBLOCK_P5P14P15P128P255P13P6P1:
	defb 5
    defb 14
    defb 15
    defb 128
    defb 255
    defb 13
    defb 6
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P24P64P0P1:
	defb 24
    defb 64
    defb 0
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P14P112P0:
	defb 14
    defb 112
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P14P160P0:
	defb 14
    defb 160
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P15P8P0P20P0P6:
	defb 15
    defb 8
    defb 0
    defb 20
    defb 0
    defb 6
JUSTADDCREAM_EFFECTBLOCK_P5P0P15P112P0P12:
	defb 5
    defb 0
    defb 15
    defb 112
    defb 0
    defb 12
JUSTADDCREAM_EFFECTBLOCK_P5P0P18P0P2:
	defb 5
    defb 0
    defb 18
    defb 0
    defb 2
JUSTADDCREAM_EFFECTBLOCK_P15P64P0P20P0P16:
	defb 15
    defb 64
    defb 0
    defb 20
    defb 0
    defb 16
JUSTADDCREAM_EFFECTBLOCK_P5P0P14P112P0:
	defb 5
    defb 0
    defb 14
    defb 112
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P5P0P14P160P0:
	defb 5
    defb 0
    defb 14
    defb 160
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P5P0P10P0:
	defb 5
    defb 0
    defb 10
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P5P0P13P8:
	defb 5
    defb 0
    defb 13
    defb 8
JUSTADDCREAM_EFFECTBLOCK_P5P0P15P64P0P6P0:
	defb 5
    defb 0
    defb 15
    defb 64
    defb 0
    defb 6
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P5P0P15P64P0P6P2:
	defb 5
    defb 0
    defb 15
    defb 64
    defb 0
    defb 6
    defb 2
JUSTADDCREAM_EFFECTBLOCK_P24P59P128P1:
	defb 24
    defb 59
    defb 128
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P14P32P0:
	defb 14
    defb 32
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P14P64P0:
	defb 14
    defb 64
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P13P18P128P1:
	defb 13
    defb 18
    defb 128
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P5P0P13P18P0P1:
	defb 5
    defb 0
    defb 13
    defb 18
    defb 0
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P14P8P0:
	defb 14
    defb 8
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P24P23P0P12:
	defb 24
    defb 23
    defb 0
    defb 12
JUSTADDCREAM_EFFECTBLOCK_P24P48P128P1:
	defb 24
    defb 48
    defb 128
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P5P0P18P0P12:
	defb 5
    defb 0
    defb 18
    defb 0
    defb 12
JUSTADDCREAM_EFFECTBLOCK_P15P112P0P12:
	defb 15
    defb 112
    defb 0
    defb 12
JUSTADDCREAM_EFFECTBLOCK_P24P57P0P3:
	defb 24
    defb 57
    defb 0
    defb 3
JUSTADDCREAM_EFFECTBLOCK_P15P64P0P6P0:
	defb 15
    defb 64
    defb 0
    defb 6
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P15P64P0P6P1:
	defb 15
    defb 64
    defb 0
    defb 6
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P15P64P0P6P2:
	defb 15
    defb 64
    defb 0
    defb 6
    defb 2
JUSTADDCREAM_EFFECTBLOCK_P5P0P6P0:
	defb 5
    defb 0
    defb 6
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P5P0P6P1:
	defb 5
    defb 0
    defb 6
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P5P0P6P2:
	defb 5
    defb 0
    defb 6
    defb 2
JUSTADDCREAM_EFFECTBLOCK_P5P0P14P64P0:
	defb 5
    defb 0
    defb 14
    defb 64
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P20P0P1:
	defb 20
    defb 0
    defb 1
JUSTADDCREAM_EFFECTBLOCK_P20P0P5:
	defb 20
    defb 0
    defb 5
JUSTADDCREAM_EFFECTBLOCK_P10P0:
	defb 10
    defb 0
JUSTADDCREAM_EFFECTBLOCK_P5P0P18P128P1:
	defb 5
    defb 0
    defb 18
    defb 128
    defb 1
JUSTADDCREAM_SUBSONG0_START:
	defb 2
    defb 0
    defb 1
    defb 4
    defb 27
    defb 6
    defb 9
JUSTADDCREAM_SUBSONG0_LINKER:
	defw JUSTADDCREAM_SUBSONG0_TRACK17
    defw JUSTADDCREAM_SUBSONG0_TRACK22
    defw JUSTADDCREAM_SUBSONG0_TRACK0
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK18
    defw JUSTADDCREAM_SUBSONG0_TRACK21
    defw JUSTADDCREAM_SUBSONG0_TRACK0
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK2
    defw JUSTADDCREAM_SUBSONG0_TRACK19
    defw JUSTADDCREAM_SUBSONG0_TRACK20
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK2
    defw JUSTADDCREAM_SUBSONG0_TRACK0
    defw JUSTADDCREAM_SUBSONG0_TRACK29
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
JUSTADDCREAM_SUBSONG0_LINKER_LOOP:
	defw JUSTADDCREAM_SUBSONG0_TRACK2
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK1
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK24
    defw JUSTADDCREAM_SUBSONG0_TRACK25
    defw JUSTADDCREAM_SUBSONG0_TRACK26
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK4
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK5
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK4
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK23
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK9
    defw JUSTADDCREAM_SUBSONG0_TRACK7
    defw JUSTADDCREAM_SUBSONG0_TRACK30
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK10
    defw JUSTADDCREAM_SUBSONG0_TRACK8
    defw JUSTADDCREAM_SUBSONG0_TRACK30
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK11
    defw JUSTADDCREAM_SUBSONG0_TRACK7
    defw JUSTADDCREAM_SUBSONG0_TRACK30
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK12
    defw JUSTADDCREAM_SUBSONG0_TRACK8
    defw JUSTADDCREAM_SUBSONG0_TRACK0
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK4
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK5
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK4
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK6
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK4
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK5
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK4
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK23
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK9
    defw JUSTADDCREAM_SUBSONG0_TRACK7
    defw JUSTADDCREAM_SUBSONG0_TRACK27
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK10
    defw JUSTADDCREAM_SUBSONG0_TRACK8
    defw JUSTADDCREAM_SUBSONG0_TRACK27
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK11
    defw JUSTADDCREAM_SUBSONG0_TRACK7
    defw JUSTADDCREAM_SUBSONG0_TRACK27
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK12
    defw JUSTADDCREAM_SUBSONG0_TRACK8
    defw JUSTADDCREAM_SUBSONG0_TRACK27
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK13
    defw JUSTADDCREAM_SUBSONG0_TRACK28
    defw JUSTADDCREAM_SUBSONG0_TRACK27
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK14
    defw JUSTADDCREAM_SUBSONG0_TRACK28
    defw JUSTADDCREAM_SUBSONG0_TRACK27
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK15
    defw JUSTADDCREAM_SUBSONG0_TRACK28
    defw JUSTADDCREAM_SUBSONG0_TRACK27
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK16
    defw JUSTADDCREAM_SUBSONG0_TRACK28
    defw JUSTADDCREAM_SUBSONG0_TRACK27
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK1
    defw JUSTADDCREAM_SUBSONG0_TRACK4
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK5
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK4
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK6
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK4
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK5
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defw JUSTADDCREAM_SUBSONG0_TRACK4
    defw JUSTADDCREAM_SUBSONG0_TRACK3
    defw JUSTADDCREAM_SUBSONG0_TRACK23
    defw JUSTADDCREAM_SUBSONG0_LINKERBLOCK0
    defb 0
    defb 0
    defw JUSTADDCREAM_SUBSONG0_LINKER_LOOP
JUSTADDCREAM_SUBSONG0_LINKERBLOCK0:
	defb 64
    defb 0
    defb 0
    defb 0
    defw JUSTADDCREAM_SUBSONG0_SPEEDTRACK0
    defw JUSTADDCREAM_SUBSONG0_EVENTTRACK0
JUSTADDCREAM_SUBSONG0_LINKERBLOCK1:
	defb 32
    defb 0
    defb 0
    defb 0
    defw JUSTADDCREAM_SUBSONG0_SPEEDTRACK0
    defw JUSTADDCREAM_SUBSONG0_EVENTTRACK0
JUSTADDCREAM_SUBSONG0_TRACK0:
	defb 128
    defb 0
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK1:
	defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 60
    defb 195
    defb 1
    defb 0
    defb 126
    defb 3
    defb 60
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 60
    defb 195
    defb 1
    defb 22
    defb 60
    defb 67
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 60
    defb 195
    defb 1
    defb 0
    defb 254
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 60
    defb 67
    defb 22
    defb 60
    defb 195
    defb 2
    defb 2
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK2:
	defb 204
    defb 3
    defb 34
    defb 62
    defb 128
    defb 0
    defb 152
    defb 3
    defb 128
    defb 0
    defb 140
    defb 3
    defb 10
    defb 12
    defb 60
    defb 15
    defb 128
    defb 0
    defb 140
    defb 3
    defb 60
    defb 17
    defb 62
    defb 128
    defb 0
    defb 133
    defb 3
    defb 128
    defb 0
    defb 145
    defb 3
    defb 60
    defb 17
    defb 15
    defb 17
    defb 60
    defb 19
    defb 60
    defb 128
    defb 0
    defb 60
    defb 148
    defb 3
    defb 62
    defb 128
    defb 0
    defb 136
    defb 3
    defb 128
    defb 0
    defb 148
    defb 3
    defb 60
    defb 20
    defb 15
    defb 20
    defb 60
    defb 22
    defb 62
    defb 128
    defb 0
    defb 143
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 138
    defb 3
    defb 128
    defb 0
    defb 143
    defb 3
    defb 60
    defb 22
    defb 10
    defb 14
    defb 60
    defb 17
    defb 128
    defb 0
    defb 142
    defb 3
    defb 60
    defb 10
    defb 128
    defb 0
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK3:
	defb 231
    defb 4
    defb 8
    defb 124
    defb 1
    defb 62
    defb 103
    defb 7
    defb 60
    defb 110
    defb 13
    defb 60
    defb 103
    defb 7
    defb 60
    defb 110
    defb 17
    defb 60
    defb 103
    defb 14
    defb 60
    defb 108
    defb 0
    defb 60
    defb 124
    defb 1
    defb 108
    defb 0
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 103
    defb 9
    defb 60
    defb 108
    defb 4
    defb 60
    defb 103
    defb 9
    defb 60
    defb 110
    defb 8
    defb 103
    defb 10
    defb 108
    defb 27
    defb 60
    defb 124
    defb 1
    defb 108
    defb 0
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 46
    defb 124
    defb 1
    defb 62
    defb 108
    defb 7
    defb 126
    defb 115
    defb 29
    defb 124
    defb 1
    defb 62
    defb 115
    defb 0
    defb 126
    defb 103
    defb 10
    defb 124
    defb 1
    defb 110
    defb 8
    defb 60
    defb 103
    defb 26
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK4:
	defb 204
    defb 5
    defb 0
    defb 62
    defb 128
    defb 0
    defb 152
    defb 6
    defb 128
    defb 0
    defb 140
    defb 3
    defb 10
    defb 140
    defb 5
    defb 60
    defb 143
    defb 3
    defb 128
    defb 0
    defb 140
    defb 6
    defb 60
    defb 145
    defb 5
    defb 62
    defb 128
    defb 0
    defb 133
    defb 5
    defb 128
    defb 0
    defb 145
    defb 6
    defb 60
    defb 145
    defb 3
    defb 15
    defb 145
    defb 5
    defb 60
    defb 147
    defb 3
    defb 60
    defb 195
    defb 2
    defb 2
    defb 60
    defb 212
    defb 5
    defb 0
    defb 60
    defb 20
    defb 128
    defb 0
    defb 136
    defb 3
    defb 128
    defb 0
    defb 148
    defb 6
    defb 60
    defb 148
    defb 3
    defb 15
    defb 148
    defb 5
    defb 60
    defb 150
    defb 3
    defb 60
    defb 195
    defb 2
    defb 2
    defb 60
    defb 207
    defb 5
    defb 0
    defb 60
    defb 128
    defb 0
    defb 60
    defb 138
    defb 3
    defb 128
    defb 0
    defb 143
    defb 6
    defb 60
    defb 150
    defb 3
    defb 10
    defb 142
    defb 5
    defb 60
    defb 17
    defb 128
    defb 0
    defb 142
    defb 6
    defb 60
    defb 138
    defb 3
    defb 128
    defb 0
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK5:
	defb 246
    defb 7
    defb 18
    defb 124
    defb 24
    defb 112
    defb 12
    defb 247
    defb 8
    defb 0
    defb 181
    defb 7
    defb 60
    defb 112
    defb 15
    defb 245
    defb 8
    defb 0
    defb 179
    defb 7
    defb 60
    defb 112
    defb 15
    defb 243
    defb 8
    defb 0
    defb 243
    defb 7
    defb 15
    defb 240
    defb 8
    defb 12
    defb 242
    defb 7
    defb 21
    defb 124
    defb 25
    defb 124
    defb 16
    defb 60
    defb 117
    defb 6
    defb 124
    defb 19
    defb 243
    defb 8
    defb 5
    defb 117
    defb 6
    defb 124
    defb 19
    defb 60
    defb 235
    defb 7
    defb 3
    defb 110
    defb 3
    defb 245
    defb 8
    defb 0
    defb 107
    defb 1
    defb 238
    defb 7
    defb 3
    defb 112
    defb 3
    defb 235
    defb 8
    defb 3
    defb 110
    defb 3
    defb 236
    defb 7
    defb 5
    defb 240
    defb 8
    defb 1
    defb 235
    defb 7
    defb 20
    defb 236
    defb 8
    defb 5
    defb 172
    defb 7
    defb 235
    defb 8
    defb 6
    defb 235
    defb 7
    defb 11
    defb 236
    defb 8
    defb 5
    defb 172
    defb 7
    defb 235
    defb 8
    defb 6
    defb 235
    defb 7
    defb 11
    defb 236
    defb 8
    defb 0
    defb 231
    defb 7
    defb 1
    defb 235
    defb 8
    defb 11
    defb 230
    defb 7
    defb 36
    defb 124
    defb 39
    defb 124
    defb 16
    defb 126
    defb 124
    defb 41
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK6:
	defb 246
    defb 7
    defb 18
    defb 124
    defb 24
    defb 112
    defb 12
    defb 247
    defb 8
    defb 0
    defb 181
    defb 7
    defb 60
    defb 112
    defb 15
    defb 245
    defb 8
    defb 0
    defb 179
    defb 7
    defb 60
    defb 112
    defb 15
    defb 243
    defb 8
    defb 0
    defb 243
    defb 7
    defb 15
    defb 240
    defb 8
    defb 12
    defb 242
    defb 7
    defb 21
    defb 124
    defb 25
    defb 124
    defb 16
    defb 60
    defb 117
    defb 6
    defb 124
    defb 19
    defb 243
    defb 8
    defb 5
    defb 117
    defb 6
    defb 124
    defb 19
    defb 60
    defb 235
    defb 7
    defb 3
    defb 110
    defb 3
    defb 245
    defb 8
    defb 0
    defb 107
    defb 1
    defb 238
    defb 7
    defb 3
    defb 112
    defb 3
    defb 235
    defb 8
    defb 3
    defb 110
    defb 3
    defb 236
    defb 7
    defb 5
    defb 240
    defb 8
    defb 1
    defb 235
    defb 7
    defb 20
    defb 236
    defb 8
    defb 5
    defb 172
    defb 7
    defb 235
    defb 8
    defb 6
    defb 235
    defb 7
    defb 11
    defb 236
    defb 8
    defb 5
    defb 172
    defb 7
    defb 235
    defb 8
    defb 6
    defb 238
    defb 7
    defb 0
    defb 124
    defb 32
    defb 60
    defb 174
    defb 8
    defb 238
    defb 7
    defb 16
    defb 62
    defb 176
    defb 8
    defb 243
    defb 7
    defb 44
    defb 238
    defb 8
    defb 16
    defb 62
    defb 241
    defb 7
    defb 31
    defb 124
    defb 30
    defb 124
    defb 16
    defb 60
    defb 112
    defb 6
    defb 242
    defb 8
    defb 5
    defb 238
    defb 7
    defb 44
    defb 240
    defb 8
    defb 43
    defb 235
    defb 7
    defb 11
    defb 238
    defb 8
    defb 0
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK7:
	defb 195
    defb 1
    defb 40
    defb 126
    defb 195
    defb 2
    defb 2
    defb 62
    defb 3
    defb 195
    defb 1
    defb 0
    defb 60
    defb 3
    defb 126
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 60
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 60
    defb 3
    defb 60
    defb 195
    defb 2
    defb 2
    defb 3
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK8:
	defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 62
    defb 195
    defb 1
    defb 0
    defb 3
    defb 60
    defb 3
    defb 60
    defb 3
    defb 60
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 60
    defb 195
    defb 2
    defb 2
    defb 62
    defb 3
    defb 195
    defb 1
    defb 0
    defb 195
    defb 2
    defb 2
    defb 195
    defb 1
    defb 0
    defb 60
    defb 195
    defb 2
    defb 2
    defb 62
    defb 3
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK9:
	defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 190
    defb 152
    defb 3
    defb 19
    defb 128
    defb 0
    defb 150
    defb 3
    defb 128
    defb 0
    defb 62
    defb 152
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 126
    defb 138
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 139
    defb 3
    defb 60
    defb 128
    defb 0
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK10:
	defb 152
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 152
    defb 3
    defb 19
    defb 128
    defb 0
    defb 150
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 152
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 126
    defb 150
    defb 3
    defb 22
    defb 128
    defb 0
    defb 60
    defb 147
    defb 3
    defb 19
    defb 128
    defb 0
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK11:
	defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 190
    defb 152
    defb 3
    defb 19
    defb 128
    defb 0
    defb 150
    defb 3
    defb 24
    defb 128
    defb 0
    defb 60
    defb 152
    defb 3
    defb 60
    defb 128
    defb 0
    defb 152
    defb 3
    defb 12
    defb 60
    defb 128
    defb 0
    defb 126
    defb 148
    defb 3
    defb 24
    defb 27
    defb 128
    defb 0
    defb 150
    defb 3
    defb 26
    defb 29
    defb 128
    defb 0
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK12:
	defb 152
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 152
    defb 3
    defb 19
    defb 128
    defb 0
    defb 150
    defb 3
    defb 60
    defb 10
    defb 128
    defb 0
    defb 152
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 62
    defb 150
    defb 3
    defb 10
    defb 60
    defb 22
    defb 60
    defb 11
    defb 60
    defb 23
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK13:
	defb 204
    defb 5
    defb 0
    defb 60
    defb 128
    defb 0
    defb 60
    defb 195
    defb 2
    defb 2
    defb 62
    defb 216
    defb 6
    defb 0
    defb 147
    defb 5
    defb 128
    defb 0
    defb 150
    defb 5
    defb 128
    defb 0
    defb 62
    defb 152
    defb 6
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 5
    defb 60
    defb 195
    defb 2
    defb 2
    defb 126
    defb 202
    defb 5
    defb 0
    defb 60
    defb 131
    defb 1
    defb 60
    defb 139
    defb 6
    defb 11
    defb 128
    defb 0
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK14:
	defb 216
    defb 5
    defb 0
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 6
    defb 60
    defb 128
    defb 0
    defb 152
    defb 5
    defb 19
    defb 128
    defb 0
    defb 150
    defb 5
    defb 60
    defb 131
    defb 1
    defb 60
    defb 152
    defb 6
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 5
    defb 60
    defb 195
    defb 2
    defb 2
    defb 62
    defb 3
    defb 214
    defb 5
    defb 0
    defb 150
    defb 6
    defb 131
    defb 1
    defb 60
    defb 147
    defb 6
    defb 147
    defb 3
    defb 128
    defb 0
    defb 195
    defb 2
    defb 2
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK15:
	defb 204
    defb 5
    defb 0
    defb 60
    defb 128
    defb 0
    defb 60
    defb 195
    defb 2
    defb 2
    defb 62
    defb 216
    defb 6
    defb 0
    defb 147
    defb 5
    defb 128
    defb 0
    defb 150
    defb 5
    defb 152
    defb 3
    defb 128
    defb 0
    defb 60
    defb 152
    defb 6
    defb 60
    defb 128
    defb 0
    defb 152
    defb 3
    defb 140
    defb 5
    defb 60
    defb 195
    defb 2
    defb 2
    defb 126
    defb 212
    defb 5
    defb 0
    defb 152
    defb 3
    defb 155
    defb 5
    defb 128
    defb 0
    defb 150
    defb 6
    defb 26
    defb 157
    defb 3
    defb 128
    defb 0
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK16:
	defb 216
    defb 5
    defb 0
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 6
    defb 60
    defb 128
    defb 0
    defb 152
    defb 5
    defb 19
    defb 128
    defb 0
    defb 150
    defb 5
    defb 60
    defb 10
    defb 128
    defb 0
    defb 152
    defb 6
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 5
    defb 60
    defb 195
    defb 2
    defb 2
    defb 62
    defb 214
    defb 6
    defb 0
    defb 138
    defb 5
    defb 195
    defb 2
    defb 2
    defb 214
    defb 5
    defb 0
    defb 60
    defb 139
    defb 6
    defb 60
    defb 151
    defb 3
    defb 195
    defb 2
    defb 2
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK17:
	defb 128
    defb 0
    defb 61
    defb 14
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 61
    defb 12
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 61
    defb 12
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 61
    defb 10
    defb 138
    defb 3
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK18:
	defb 204
    defb 3
    defb 0
    defb 60
    defb 128
    defb 0
    defb 254
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 254
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 254
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 140
    defb 3
    defb 60
    defb 128
    defb 0
    defb 60
    defb 143
    defb 3
    defb 62
    defb 124
    defb 23
    defb 62
    defb 128
    defb 0
    defb 60
    defb 205
    defb 3
    defb 35
    defb 124
    defb 38
    defb 62
    defb 124
    defb 23
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK19:
	defb 124
    defb 42
    defb 61
    defb 22
    defb 124
    defb 45
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK20:
	defb 128
    defb 0
    defb 61
    defb 52
    defb 195
    defb 1
    defb 0
    defb 60
    defb 195
    defb 2
    defb 2
    defb 126
    defb 3
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK21:
	defb 231
    defb 4
    defb 8
    defb 124
    defb 1
    defb 62
    defb 103
    defb 7
    defb 60
    defb 110
    defb 13
    defb 60
    defb 103
    defb 7
    defb 60
    defb 110
    defb 17
    defb 60
    defb 103
    defb 14
    defb 60
    defb 108
    defb 0
    defb 60
    defb 124
    defb 1
    defb 108
    defb 0
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 103
    defb 9
    defb 60
    defb 108
    defb 4
    defb 60
    defb 103
    defb 9
    defb 60
    defb 110
    defb 8
    defb 103
    defb 10
    defb 108
    defb 27
    defb 60
    defb 124
    defb 1
    defb 108
    defb 0
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 46
    defb 124
    defb 1
    defb 62
    defb 108
    defb 7
    defb 126
    defb 115
    defb 29
    defb 124
    defb 1
    defb 62
    defb 115
    defb 0
    defb 126
    defb 103
    defb 10
    defb 124
    defb 1
    defb 110
    defb 8
    defb 60
    defb 103
    defb 27
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK22:
	defb 231
    defb 4
    defb 28
    defb 126
    defb 103
    defb 0
    defb 60
    defb 110
    defb 13
    defb 60
    defb 103
    defb 7
    defb 60
    defb 110
    defb 17
    defb 60
    defb 103
    defb 14
    defb 60
    defb 108
    defb 0
    defb 60
    defb 124
    defb 1
    defb 108
    defb 0
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 103
    defb 9
    defb 60
    defb 108
    defb 4
    defb 60
    defb 103
    defb 9
    defb 60
    defb 110
    defb 8
    defb 103
    defb 10
    defb 108
    defb 27
    defb 60
    defb 124
    defb 1
    defb 108
    defb 0
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 46
    defb 124
    defb 1
    defb 62
    defb 108
    defb 7
    defb 126
    defb 115
    defb 29
    defb 124
    defb 1
    defb 62
    defb 115
    defb 0
    defb 126
    defb 103
    defb 10
    defb 124
    defb 1
    defb 110
    defb 8
    defb 60
    defb 103
    defb 26
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK23:
	defb 246
    defb 7
    defb 18
    defb 124
    defb 24
    defb 112
    defb 12
    defb 247
    defb 8
    defb 0
    defb 181
    defb 7
    defb 60
    defb 112
    defb 15
    defb 245
    defb 8
    defb 0
    defb 179
    defb 7
    defb 60
    defb 112
    defb 15
    defb 243
    defb 8
    defb 0
    defb 243
    defb 7
    defb 15
    defb 240
    defb 8
    defb 12
    defb 242
    defb 7
    defb 21
    defb 124
    defb 25
    defb 124
    defb 16
    defb 60
    defb 117
    defb 6
    defb 124
    defb 19
    defb 243
    defb 8
    defb 5
    defb 117
    defb 6
    defb 124
    defb 19
    defb 60
    defb 235
    defb 7
    defb 3
    defb 110
    defb 3
    defb 245
    defb 8
    defb 0
    defb 107
    defb 1
    defb 238
    defb 7
    defb 3
    defb 112
    defb 3
    defb 235
    defb 8
    defb 3
    defb 110
    defb 3
    defb 236
    defb 7
    defb 5
    defb 240
    defb 8
    defb 1
    defb 235
    defb 7
    defb 20
    defb 236
    defb 8
    defb 5
    defb 172
    defb 7
    defb 235
    defb 8
    defb 6
    defb 235
    defb 7
    defb 11
    defb 236
    defb 8
    defb 5
    defb 172
    defb 7
    defb 235
    defb 8
    defb 6
    defb 238
    defb 7
    defb 0
    defb 124
    defb 32
    defb 60
    defb 174
    defb 8
    defb 238
    defb 7
    defb 16
    defb 62
    defb 176
    defb 8
    defb 243
    defb 7
    defb 44
    defb 238
    defb 8
    defb 16
    defb 62
    defb 241
    defb 7
    defb 31
    defb 124
    defb 30
    defb 124
    defb 16
    defb 60
    defb 112
    defb 6
    defb 242
    defb 8
    defb 5
    defb 174
    defb 7
    defb 60
    defb 124
    defb 33
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK24:
	defb 204
    defb 3
    defb 34
    defb 62
    defb 128
    defb 0
    defb 152
    defb 3
    defb 128
    defb 0
    defb 140
    defb 3
    defb 10
    defb 12
    defb 60
    defb 15
    defb 128
    defb 0
    defb 140
    defb 3
    defb 60
    defb 17
    defb 62
    defb 128
    defb 0
    defb 133
    defb 3
    defb 128
    defb 0
    defb 145
    defb 3
    defb 60
    defb 17
    defb 15
    defb 17
    defb 60
    defb 19
    defb 60
    defb 128
    defb 0
    defb 60
    defb 148
    defb 3
    defb 62
    defb 128
    defb 0
    defb 136
    defb 3
    defb 128
    defb 0
    defb 148
    defb 3
    defb 60
    defb 20
    defb 15
    defb 20
    defb 60
    defb 22
    defb 62
    defb 128
    defb 0
    defb 143
    defb 3
    defb 126
    defb 15
    defb 60
    defb 128
    defb 0
    defb 61
    defb 5
    defb 152
    defb 3
    defb 12
    defb 60
    defb 10
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK25:
	defb 231
    defb 4
    defb 8
    defb 124
    defb 1
    defb 62
    defb 103
    defb 7
    defb 60
    defb 110
    defb 13
    defb 60
    defb 103
    defb 7
    defb 60
    defb 110
    defb 17
    defb 60
    defb 103
    defb 14
    defb 60
    defb 108
    defb 0
    defb 60
    defb 124
    defb 1
    defb 108
    defb 0
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 103
    defb 9
    defb 60
    defb 108
    defb 4
    defb 60
    defb 103
    defb 9
    defb 60
    defb 110
    defb 8
    defb 103
    defb 10
    defb 108
    defb 27
    defb 60
    defb 124
    defb 1
    defb 108
    defb 0
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 103
    defb 10
    defb 124
    defb 1
    defb 108
    defb 4
    defb 60
    defb 46
    defb 124
    defb 1
    defb 62
    defb 108
    defb 7
    defb 126
    defb 115
    defb 29
    defb 124
    defb 1
    defb 62
    defb 115
    defb 47
    defb 124
    defb 1
    defb 115
    defb 46
    defb 60
    defb 115
    defb 37
    defb 124
    defb 1
    defb 115
    defb 22
    defb 60
    defb 115
    defb 0
    defb 124
    defb 1
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK26:
	defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 60
    defb 195
    defb 1
    defb 0
    defb 126
    defb 3
    defb 60
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 60
    defb 195
    defb 1
    defb 22
    defb 60
    defb 67
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 60
    defb 195
    defb 1
    defb 0
    defb 126
    defb 3
    defb 61
    defb 8
    defb 195
    defb 2
    defb 22
    defb 60
    defb 67
    defb 2
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK27:
	defb 171
    defb 11
    defb 48
    defb 243
    defb 9
    defb 0
    defb 50
    defb 179
    defb 10
    defb 174
    defb 9
    defb 178
    defb 10
    defb 179
    defb 11
    defb 179
    defb 9
    defb 50
    defb 179
    defb 11
    defb 174
    defb 9
    defb 178
    defb 10
    defb 179
    defb 11
    defb 174
    defb 10
    defb 178
    defb 11
    defb 51
    defb 46
    defb 171
    defb 9
    defb 46
    defb 174
    defb 11
    defb 176
    defb 9
    defb 174
    defb 10
    defb 43
    defb 171
    defb 9
    defb 46
    defb 171
    defb 10
    defb 176
    defb 9
    defb 174
    defb 10
    defb 171
    defb 11
    defb 176
    defb 10
    defb 174
    defb 11
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK28:
	defb 174
    defb 11
    defb 51
    defb 247
    defb 9
    defb 0
    defb 53
    defb 183
    defb 10
    defb 178
    defb 9
    defb 181
    defb 10
    defb 183
    defb 11
    defb 183
    defb 9
    defb 53
    defb 183
    defb 11
    defb 178
    defb 9
    defb 181
    defb 10
    defb 183
    defb 11
    defb 178
    defb 10
    defb 181
    defb 11
    defb 55
    defb 50
    defb 174
    defb 9
    defb 50
    defb 178
    defb 11
    defb 179
    defb 9
    defb 178
    defb 10
    defb 46
    defb 174
    defb 9
    defb 50
    defb 174
    defb 11
    defb 179
    defb 9
    defb 178
    defb 10
    defb 174
    defb 11
    defb 179
    defb 10
    defb 178
    defb 11
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK29:
	defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 60
    defb 195
    defb 1
    defb 0
    defb 126
    defb 3
    defb 60
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 60
    defb 195
    defb 1
    defb 22
    defb 60
    defb 67
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 126
    defb 195
    defb 2
    defb 2
    defb 60
    defb 195
    defb 1
    defb 0
    defb 254
    defb 195
    defb 2
    defb 2
    defb 126
    defb 195
    defb 1
    defb 0
    defb 60
    defb 67
    defb 22
    defb 60
    defb 195
    defb 2
    defb 2
    defb 60
    defb 67
    defb 37
    defb 67
    defb 2
    defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_TRACK30:
	defb 61
    defb 127
JUSTADDCREAM_SUBSONG0_SPEEDTRACK0:
	defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 14
    defb 10
    defb 127
JUSTADDCREAM_SUBSONG0_EVENTTRACK0:
	defb 255
